// Code generated by floret-host-init v1 for profile production-recovery. Host-owned; review before editing.

package composition

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	"github.com/floegence/floret/config"
	floretruntime "github.com/floegence/floret/runtime"
)

type floretSmokeCatalog struct{}

func (floretSmokeCatalog) ListFloretRootThreadIDs(context.Context) ([]floretruntime.ThreadID, error) {
	return nil, nil
}

func TestFloretGeneratedCompositionSmoke(t *testing.T) {
	ctx := context.Background()
	cfg := config.Config{
		Provider: config.ProviderFake, Model: "fake-model", FakeResponse: "Hello from Floret.",
		AgentProfile: config.AgentProfile{ID: "smoke-agent", Name: "Smoke Agent", SystemPrompt: "Answer briefly."},
	}
	composition, err := openFloretComposition(ctx, filepath.Join(t.TempDir(), "floret.db"), floretruntime.SQLiteStartupRequest{}, nil, floretSmokeCatalog{}, nil, cfg)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := composition.close(); err != nil {
			t.Error(err)
		}
	})

	threadID := floretruntime.ThreadID("smoke-thread")
	intentID := floretruntime.CreateIntentID("create-smoke-thread")
	creator, err := composition.bindThreadCreator(threadID, intentID)
	if err != nil {
		t.Fatal(err)
	}
	thread, err := creator.CreateThread(ctx, floretruntime.CreateThreadRequest{ThreadID: threadID, CreateIntentID: intentID})
	if err != nil {
		t.Fatal(err)
	}
	turns, err := composition.bindTurnHost(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	result, runErr := turns.RunTurn(ctx, floretruntime.RunTurnRequest{
		ThreadID: thread.ID, TurnID: "smoke-turn", RunID: "smoke-run",
		Input: floretruntime.TurnInput{Text: "Say hello."},
	})
	if err := validateFloretTurnOutcome(result, runErr); err != nil {
		t.Fatal(err)
	}
	reader, err := composition.bindThreadReader(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := reader.ReadThread(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	if snapshot.ID != thread.ID || result.Output != "Hello from Floret." {
		t.Fatalf("unexpected smoke result: thread=%#v turn=%#v", snapshot, result)
	}
	children, err := composition.bindSubAgentHost(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	child, err := children.SpawnSubAgent(ctx, floretruntime.SpawnSubAgentRequest{
		PublicationID: "publish-smoke-child", ParentThreadID: thread.ID, ParentTurnID: "smoke-turn",
		ThreadID: "smoke-child", TaskName: "smoke", TaskDescription: "exercise generated SubAgent wiring",
		Message: "Return a short handoff.", HostProfileRef: "smoke", ForkMode: floretruntime.SubAgentForkNone,
	})
	if err != nil {
		t.Fatal(err)
	}
	waited, err := children.WaitSubAgents(ctx, floretruntime.WaitSubAgentsRequest{
		ParentThreadID: thread.ID, ChildThreadIDs: []floretruntime.ThreadID{child.ThreadID}, Timeout: 2 * time.Second,
	})
	if err != nil {
		t.Fatal(err)
	}
	if waited.TimedOut || len(waited.Snapshots) != 1 || waited.Snapshots[0].Status != floretruntime.SubAgentStatusCompleted {
		t.Fatalf("unexpected SubAgent smoke result: %#v", waited)
	}
}
