// Code generated by floret-host-init v1 for profile production-recovery. Host-owned; review before editing.

package composition

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/floegence/floret/config"
	floretruntime "github.com/floegence/floret/runtime"
)

type floretComposition struct {
	store        *floretruntime.Store
	create       *floretruntime.ThreadCreateHostBinder
	read         *floretruntime.ThreadReadHostBinder
	turn         *floretruntime.TurnExecutionHostBinder
	turnOptions  floretruntime.TurnExecutionHostOptions
	subAgent     *floretruntime.SubAgentHostBinder
	subAgentRead *floretruntime.SubAgentReadHostBinder
	interrupted  *floretruntime.InterruptedTurnRecoveryHostBinder
	pending      *floretruntime.PendingToolRecoveryHostBinder
}

type floretThreadCreator interface {
	CreateThread(context.Context, floretruntime.CreateThreadRequest) (floretruntime.ThreadSummary, error)
}

type floretThreadReader interface {
	ReadThread(context.Context, floretruntime.ThreadID) (floretruntime.ThreadSnapshot, error)
	ReadThreadOverview(context.Context, floretruntime.ThreadID) (floretruntime.ThreadOverview, error)
	ListPendingToolSettlementTargets(context.Context, floretruntime.ThreadID) ([]floretruntime.PendingToolSettlementTarget, error)
}

type floretTurnRunner interface {
	RunTurn(context.Context, floretruntime.RunTurnRequest) (floretruntime.TurnResult, error)
}

type floretSubAgentRunner interface {
	SpawnSubAgent(context.Context, floretruntime.SpawnSubAgentRequest) (floretruntime.SubAgentSnapshot, error)
	SendSubAgentInput(context.Context, floretruntime.SendSubAgentInputRequest) (floretruntime.SubAgentSnapshot, error)
	WaitSubAgents(context.Context, floretruntime.WaitSubAgentsRequest) (floretruntime.WaitSubAgentsResult, error)
	CloseSubAgent(context.Context, floretruntime.CloseSubAgentRequest) (floretruntime.SubAgentSnapshot, error)
}

type floretRootCatalog interface {
	ListFloretRootThreadIDs(context.Context) ([]floretruntime.ThreadID, error)
}

type floretPendingToolReconciler interface {
	ReconcileFloretPendingTool(context.Context, floretruntime.ThreadID, floretruntime.PendingToolSettlementTarget) (floretruntime.PendingToolSettlementRequest, bool, error)
}

type floretRecoveryNode struct {
	parentThreadID floretruntime.ThreadID
	threadID       floretruntime.ThreadID
	depth          int
}

type FloretRecoveryTraversalLimitError struct {
	Kind     string
	Limit    int
	ThreadID floretruntime.ThreadID
}

func (e *FloretRecoveryTraversalLimitError) Error() string {
	if e == nil {
		return "floret recovery traversal limit exceeded"
	}
	return fmt.Sprintf("floret recovery %s limit %d exceeded at %q", e.Kind, e.Limit, e.ThreadID)
}

const (
	floretRecoveryMaxDepth = 64
	floretRecoveryMaxNodes = 10000
)

func openFloretComposition(ctx context.Context, databasePath string, startup floretruntime.SQLiteStartupRequest, storeOptions []floretruntime.SQLiteStoreOption, catalog floretRootCatalog, reconciler floretPendingToolReconciler, cfg config.Config, options ...floretruntime.TurnExecutionOption) (*floretComposition, error) {
	turnOptions, err := floretruntime.NewTurnExecutionOptions(cfg, options...)
	if err != nil {
		return nil, err
	}
	startupResult, err := floretruntime.StartSQLiteStore(ctx, databasePath, startup, storeOptions...)
	if err != nil {
		return nil, err
	}
	composition := &floretComposition{store: startupResult.Store, turnOptions: turnOptions}
	err = floretruntime.ConfigureHostCapabilities(composition.store, func(bootstrap *floretruntime.HostBootstrap) error {
		if composition.create, err = floretruntime.NewThreadCreateHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.read, err = floretruntime.NewThreadReadHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.turn, err = floretruntime.NewTurnExecutionHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.subAgent, err = floretruntime.NewSubAgentHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.subAgentRead, err = floretruntime.NewSubAgentReadHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.interrupted, err = floretruntime.NewInterruptedTurnRecoveryHostBinder(bootstrap); err != nil {
			return err
		}
		composition.pending, err = floretruntime.NewPendingToolRecoveryHostBinder(bootstrap)
		return err
	})
	if err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	if err := composition.recoverBeforeReady(ctx, catalog, reconciler); err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	return composition, nil
}

func (composition *floretComposition) close() error {
	if composition == nil || composition.store == nil {
		return nil
	}
	return composition.store.Close()
}

func (composition *floretComposition) bindThreadCreator(threadID floretruntime.ThreadID, createIntentID floretruntime.CreateIntentID) (floretThreadCreator, error) {
	if composition == nil || composition.create == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.create.Bind(threadID, createIntentID)
}

func (composition *floretComposition) bindThreadReader(ctx context.Context, threadID floretruntime.ThreadID) (floretThreadReader, error) {
	if composition == nil || composition.read == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.read.NewHost(ctx, threadID)
}

func (composition *floretComposition) bindTurnHost(ctx context.Context, threadID floretruntime.ThreadID) (floretTurnRunner, error) {
	if composition == nil || composition.turn == nil {
		return nil, errors.New("floret composition is not open")
	}
	factory, err := composition.turn.Bind(threadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, composition.turnOptions)
}

func (composition *floretComposition) bindSubAgentHost(ctx context.Context, parentThreadID floretruntime.ThreadID) (floretSubAgentRunner, error) {
	if composition == nil || composition.subAgent == nil {
		return nil, errors.New("floret composition has no SubAgent capability")
	}
	factory, err := composition.subAgent.Bind(parentThreadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, floretruntime.SubAgentHostOptions{
		Config:                   composition.turnOptions.Config,
		ModelGateway:             composition.turnOptions.ModelGateway,
		ModelGatewayIdentity:     composition.turnOptions.ModelGatewayIdentity,
		ModelGatewayCapabilities: composition.turnOptions.ModelGatewayCapabilities,
		Tools:                    composition.turnOptions.Tools,
		EffectAuthorizationGate:  composition.turnOptions.EffectAuthorizationGate,
		Sink:                     composition.turnOptions.Sink,
		ToolSurfaceProvider:      composition.turnOptions.ToolSurfaceProvider,
		IDGenerator:              composition.turnOptions.IDGenerator,
		LoopLimits:               composition.turnOptions.LoopLimits,
		Capabilities:             composition.turnOptions.Capabilities,
		ThreadTitleMode:          composition.turnOptions.ThreadTitleMode,
	})
}

func validateFloretTurnOutcome(result floretruntime.TurnResult, runErr error) error {
	if err := result.Validate(); err != nil {
		return errors.Join(runErr, fmt.Errorf("invalid turn outcome: %w", err))
	}
	if !result.Status.IsTerminal() {
		return errors.Join(runErr, fmt.Errorf("turn outcome is not terminal: %s", result.Status))
	}
	return runErr
}

func (composition *floretComposition) recoverBeforeReady(ctx context.Context, catalog floretRootCatalog, reconciler floretPendingToolReconciler) error {
	if catalog == nil {
		return errors.New("production-recovery requires a root catalog")
	}
	roots, err := catalog.ListFloretRootThreadIDs(ctx)
	if err != nil {
		return fmt.Errorf("list Floret roots: %w", err)
	}
	sort.Slice(roots, func(left, right int) bool { return roots[left] < roots[right] })
	parents := make(map[floretruntime.ThreadID]floretruntime.ThreadID, len(roots))
	queue := make([]floretRecoveryNode, 0, len(roots))
	for _, root := range roots {
		if strings.TrimSpace(string(root)) == "" {
			return errors.New("production root catalog contains an empty thread id")
		}
		if _, exists := parents[root]; exists {
			return fmt.Errorf("production root catalog repeats thread %q", root)
		}
		if len(parents) >= floretRecoveryMaxNodes {
			return &FloretRecoveryTraversalLimitError{Kind: "node", Limit: floretRecoveryMaxNodes, ThreadID: root}
		}
		parents[root] = ""
		if err := composition.recoverRoot(ctx, root); err != nil {
			return err
		}
		reader, err := composition.bindThreadReader(ctx, root)
		if err != nil {
			return err
		}
		targets, err := reader.ListPendingToolSettlementTargets(ctx, root)
		if err != nil {
			return err
		}
		if err := composition.settlePending(ctx, "", targets, reconciler); err != nil {
			return err
		}
		queue = append(queue, floretRecoveryNode{threadID: root})
	}
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		if node.depth >= floretRecoveryMaxDepth {
			return &FloretRecoveryTraversalLimitError{Kind: "depth", Limit: floretRecoveryMaxDepth, ThreadID: node.threadID}
		}
		reader, err := composition.subAgentRead.NewHost(ctx, node.threadID)
		if err != nil {
			return err
		}
		children, err := reader.ListSubAgents(ctx, node.threadID)
		if err != nil {
			return err
		}
		sort.Slice(children, func(left, right int) bool { return children[left].ThreadID < children[right].ThreadID })
		for _, child := range children {
			if child.ParentThreadID != node.threadID || strings.TrimSpace(string(child.ThreadID)) == "" || child.ThreadID == node.threadID {
				return fmt.Errorf("corrupt SubAgent authority under parent %q", node.threadID)
			}
			if previous, exists := parents[child.ThreadID]; exists {
				return fmt.Errorf("SubAgent %q appears under parents %q and %q", child.ThreadID, previous, node.threadID)
			}
			if len(parents) >= floretRecoveryMaxNodes {
				return &FloretRecoveryTraversalLimitError{Kind: "node", Limit: floretRecoveryMaxNodes, ThreadID: child.ThreadID}
			}
			parents[child.ThreadID] = node.threadID
			if err := composition.recoverChild(ctx, child); err != nil {
				return err
			}
			targets, err := reader.ListPendingToolSettlementTargets(ctx, floretruntime.ListSubAgentPendingToolSettlementTargetsRequest{
				ParentThreadID: node.threadID, ChildThreadID: child.ThreadID,
			})
			if err != nil {
				return err
			}
			if err := composition.settlePending(ctx, node.threadID, targets, reconciler); err != nil {
				return err
			}
			queue = append(queue, floretRecoveryNode{parentThreadID: node.threadID, threadID: child.ThreadID, depth: node.depth + 1})
		}
	}
	return nil
}

func (composition *floretComposition) recoverRoot(ctx context.Context, threadID floretruntime.ThreadID) error {
	reader, err := composition.bindThreadReader(ctx, threadID)
	if err != nil {
		return err
	}
	overview, err := reader.ReadThreadOverview(ctx, threadID)
	if err != nil {
		return err
	}
	switch overview.Thread.Status {
	case floretruntime.ThreadStatusInterrupted:
		factory, err := composition.interrupted.BindThread(ctx, threadID)
		if err != nil {
			return err
		}
		host, err := factory.NewHost(ctx, nil)
		if err != nil {
			return err
		}
		_, err = host.RecoverInterruptedTurn(ctx)
		return err
	case floretruntime.ThreadStatusRunning:
		return fmt.Errorf("root %q still has an active owner", threadID)
	case floretruntime.ThreadStatusIdle, floretruntime.ThreadStatusWaiting, floretruntime.ThreadStatusCompleted,
		floretruntime.ThreadStatusFailed, floretruntime.ThreadStatusCancelled:
		return nil
	default:
		return fmt.Errorf("root %q has unsupported startup status %q", threadID, overview.Thread.Status)
	}
}

func (composition *floretComposition) recoverChild(ctx context.Context, child floretruntime.SubAgentSnapshot) error {
	switch child.Status {
	case floretruntime.SubAgentStatusInterrupted:
		factory, err := composition.interrupted.BindSubAgent(ctx, child.ParentThreadID, child.ThreadID)
		if err != nil {
			return err
		}
		host, err := factory.NewHost(ctx, nil)
		if err != nil {
			return err
		}
		_, err = host.RecoverInterruptedTurn(ctx)
		return err
	case floretruntime.SubAgentStatusRunning, floretruntime.SubAgentStatusClosing:
		return fmt.Errorf("SubAgent %q still has an active owner", child.ThreadID)
	case floretruntime.SubAgentStatusIdle, floretruntime.SubAgentStatusWaiting, floretruntime.SubAgentStatusCompleted,
		floretruntime.SubAgentStatusFailed, floretruntime.SubAgentStatusCancelled, floretruntime.SubAgentStatusClosed:
		return nil
	default:
		return fmt.Errorf("SubAgent %q has unsupported startup status %q", child.ThreadID, child.Status)
	}
}

func (composition *floretComposition) settlePending(ctx context.Context, parentThreadID floretruntime.ThreadID, targets []floretruntime.PendingToolSettlementTarget, reconciler floretPendingToolReconciler) error {
	for _, target := range targets {
		if reconciler == nil {
			return fmt.Errorf("pending tool %q requires host reconciliation", target.ToolCallID)
		}
		request, ready, err := reconciler.ReconcileFloretPendingTool(ctx, parentThreadID, target)
		if err != nil {
			return err
		}
		if !ready {
			return fmt.Errorf("pending tool %q is not reconciled", target.ToolCallID)
		}
		if request.Target != target {
			return fmt.Errorf("pending tool reconciler changed target %q", target.ToolCallID)
		}
		var host *floretruntime.PendingToolRecoveryHost
		if parentThreadID == "" {
			host, err = composition.pending.NewThreadHost(ctx, target.ThreadID, nil)
		} else {
			host, err = composition.pending.NewSubAgentHost(ctx, parentThreadID, nil)
		}
		if err != nil {
			return err
		}
		if _, err := host.SettlePendingTool(ctx, request); err != nil {
			return err
		}
	}
	return nil
}
