// Code generated by genbackendrepo; DO NOT EDIT.

package sessiontree

import (
	"context"

	"github.com/floegence/floret/v2/internal/session/artifact"
)

func (repo *BackendRepo) AcquireThreadAuthorityClaim(ctx context.Context, operationID string, requiredSourceThreadIDs, authorityThreadIDs []string) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.AcquireThreadAuthorityClaim(ctx, operationID, requiredSourceThreadIDs, authorityThreadIDs)
	})
	return err
}

func (repo *BackendRepo) AcquireTurnLease(ctx context.Context, request TurnLease) (TurnLease, error) {
	var result0 TurnLease
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.AcquireTurnLease(ctx, request)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ActiveTurnLease(ctx context.Context, threadID string) (TurnLease, bool, error) {
	var result0 TurnLease
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ActiveTurnLease(ctx, threadID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) AdmitPendingToolCompletion(ctx context.Context, req AdmitPendingToolCompletionRequest) (AdmitPendingToolCompletionResult, error) {
	var result0 AdmitPendingToolCompletionResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.AdmitPendingToolCompletion(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) AdmitSubAgentInput(ctx context.Context, req AdmitSubAgentInputRequest) (AdmitSubAgentInputResult, error) {
	var result0 AdmitSubAgentInputResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.AdmitSubAgentInput(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) AdmitTurn(ctx context.Context, req AdmitTurnRequest) (AdmitTurnResult, error) {
	var result0 AdmitTurnResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.AdmitTurn(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Append(ctx context.Context, entry Entry, opts AppendOptions) (Entry, error) {
	var result0 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Append(ctx, entry, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Approval(ctx context.Context, approvalID string) (ApprovalRecord, error) {
	var result0 ApprovalRecord
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Approval(ctx, approvalID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ArtifactClosure(ctx context.Context, req ArtifactClosureRequest) (artifact.Closure, error) {
	var result0 artifact.Closure
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ArtifactClosure(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) BeginAutomaticThreadTitle(ctx context.Context, req BeginAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.BeginAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) BeginCompaction(ctx context.Context, req BeginCompactionRequest) (BeginCompactionResult, error) {
	var result0 BeginCompactionResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.BeginCompaction(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) BeginEffectDispatch(ctx context.Context, req BeginEffectDispatchRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.BeginEffectDispatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CancelApprovalBatch(ctx context.Context, req CancelApprovalBatchRequest) (CancelApprovalBatchResult, error) {
	var result0 CancelApprovalBatchResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CancelApprovalBatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CanonicalTurnEntries(ctx context.Context, threadID, turnID, runID string) ([]Entry, bool, error) {
	var result0 []Entry
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.CanonicalTurnEntries(ctx, threadID, turnID, runID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) CommitApprovalDispatch(ctx context.Context, req CommitApprovalDispatchRequest) (CommitApprovalDispatchResult, error) {
	var result0 CommitApprovalDispatchResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CommitApprovalDispatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CompareAndSwapAgentTodoState(ctx context.Context, state AgentTodoState, expectedVersion int64) (AgentTodoState, error) {
	var result0 AgentTodoState
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CompareAndSwapAgentTodoState(ctx, state, expectedVersion)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CompleteAutomaticThreadTitle(ctx context.Context, req CompleteAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CompleteAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CreateRoot(ctx context.Context, req CreateRootRequest) (CreateRootResult, error) {
	var result0 CreateRootResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CreateRoot(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CreateThread(ctx context.Context, meta ThreadMeta) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CreateThread(ctx, meta)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CreateThreadWithInitialEntry(ctx context.Context, meta ThreadMeta, initial Entry) (ThreadMeta, Entry, error) {
	var result0 ThreadMeta
	var result1 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.CreateThreadWithInitialEntry(ctx, meta, initial)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) DeleteProviderState(ctx context.Context, threadID string) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.DeleteProviderState(ctx, threadID)
	})
	return err
}

func (repo *BackendRepo) DeleteRootTree(ctx context.Context, rootThreadID string) (DeleteRootTreeResult, error) {
	var result0 DeleteRootTreeResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.DeleteRootTree(ctx, rootThreadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Entries(ctx context.Context, threadID string) ([]Entry, error) {
	var result0 []Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Entries(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Entry(ctx context.Context, threadID, entryID string) (Entry, error) {
	var result0 Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Entry(ctx, threadID, entryID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FailAutomaticThreadTitle(ctx context.Context, req FailAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FailAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinalizeApproval(ctx context.Context, req FinalizeApprovalRequest) (FinalizeApprovalResult, error) {
	var result0 FinalizeApprovalResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinalizeApproval(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishCompaction(ctx context.Context, req FinishCompactionRequest) (FinishCompactionResult, error) {
	var result0 FinishCompactionResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishCompaction(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishEffectDispatch(ctx context.Context, req FinishEffectDispatchRequest) (FinishEffectDispatchResult, error) {
	var result0 FinishEffectDispatchResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishEffectDispatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishSubAgentClose(ctx context.Context, req FinishSubAgentCloseRequest) (FinishSubAgentCloseResult, error) {
	var result0 FinishSubAgentCloseResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishSubAgentClose(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishTurn(ctx context.Context, req FinishTurnRequest) (FinishTurnResult, error) {
	var result0 FinishTurnResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishTurn(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Fork(ctx context.Context, opts ForkOptions) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Fork(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ForkWithInitialEntry(ctx context.Context, opts ForkOptions, initial Entry) (ThreadMeta, Entry, error) {
	var result0 ThreadMeta
	var result1 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ForkWithInitialEntry(ctx, opts, initial)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) InspectSubAgentThreadAuthority(ctx context.Context, parentThreadID, childThreadID string) (SubAgentThreadAuthoritySnapshot, error) {
	var result0 SubAgentThreadAuthoritySnapshot
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.InspectSubAgentThreadAuthority(ctx, parentThreadID, childThreadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) InspectThreadAuthority(ctx context.Context, threadID string) (ThreadAuthoritySnapshot, error) {
	var result0 ThreadAuthoritySnapshot
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.InspectThreadAuthority(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ListCanonicalTurns(ctx context.Context, opts ListCanonicalTurnsOptions) (CanonicalTurnsPage, error) {
	var result0 CanonicalTurnsPage
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ListCanonicalTurns(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ListSubAgentInputs(ctx context.Context, childThreadID string, state SubAgentInputState) ([]SubAgentInputRecord, error) {
	var result0 []SubAgentInputRecord
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ListSubAgentInputs(ctx, childThreadID, state)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ListThreads(ctx context.Context, opts ListThreadsOptions) ([]ThreadMeta, error) {
	var result0 []ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ListThreads(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) MarkEffectUnknown(ctx context.Context, req MarkEffectUnknownRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.MarkEffectUnknown(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) MoveLeaf(ctx context.Context, threadID, entryID string) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.MoveLeaf(ctx, threadID, entryID)
	})
	return err
}

func (repo *BackendRepo) Path(ctx context.Context, threadID, leafID string) ([]Entry, error) {
	var result0 []Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Path(ctx, threadID, leafID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PathPage(ctx context.Context, threadID, leafID, beforeEntryID string, limit int) (PathPage, error) {
	var result0 PathPage
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PathPage(ctx, threadID, leafID, beforeEntryID, limit)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PendingAutomaticThreadTitles(ctx context.Context) ([]ThreadMeta, error) {
	var result0 []ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PendingAutomaticThreadTitles(ctx)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PrepareApprovalBatch(ctx context.Context, req PrepareApprovalBatchRequest) (PrepareApprovalBatchResult, error) {
	var result0 PrepareApprovalBatchResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PrepareApprovalBatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PrepareEffectAttempt(ctx context.Context, req PrepareEffectAttemptRequest) (PrepareEffectAttemptResult, error) {
	var result0 PrepareEffectAttemptResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PrepareEffectAttempt(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PrepareForkClaim(ctx context.Context, operationID, rootThreadID string, nodes []ForkOptions) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.PrepareForkClaim(ctx, operationID, rootThreadID, nodes)
	})
	return err
}

func (repo *BackendRepo) PrepareSubAgentClose(ctx context.Context, req PrepareSubAgentCloseRequest) (PrepareSubAgentCloseResult, error) {
	var result0 PrepareSubAgentCloseResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PrepareSubAgentClose(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ProviderState(ctx context.Context, threadID string) (ProviderStateRecord, error) {
	var result0 ProviderStateRecord
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ProviderState(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PublishSubAgent(ctx context.Context, req PublishSubAgentRequest) (PublishSubAgentResult, error) {
	var result0 PublishSubAgentResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PublishSubAgent(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PublishSubAgentInput(ctx context.Context, req PublishSubAgentInputRequest) (SubAgentInputRecord, bool, error) {
	var result0 SubAgentInputRecord
	var result1 bool
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.PublishSubAgentInput(ctx, req)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) PublishSubAgentPendingToolCompletion(ctx context.Context, req PublishSubAgentPendingToolCompletionRequest) (PublishSubAgentPendingToolCompletionResult, error) {
	var result0 PublishSubAgentPendingToolCompletionResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PublishSubAgentPendingToolCompletion(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PutProviderState(ctx context.Context, record ProviderStateRecord) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.PutProviderState(ctx, record)
	})
	return err
}

func (repo *BackendRepo) ReadAgentTodoState(ctx context.Context, threadID string) (AgentTodoState, error) {
	var result0 AgentTodoState
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadAgentTodoState(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadApprovalQueue(ctx context.Context, threadID string) (ApprovalQueue, error) {
	var result0 ApprovalQueue
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadApprovalQueue(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadArtifact(ctx context.Context, req ArtifactReadRequest) (ArtifactContent, error) {
	var result0 ArtifactContent
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadArtifact(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadCanonicalTurn(ctx context.Context, threadID, turnID string) (CanonicalTurnRead, error) {
	var result0 CanonicalTurnRead
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadCanonicalTurn(ctx, threadID, turnID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadCompaction(ctx context.Context, threadID, requestID string) (CompactionOperation, bool, error) {
	var result0 CompactionOperation
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ReadCompaction(ctx, threadID, requestID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) ReadPendingToolCompletion(ctx context.Context, req AdmitPendingToolCompletionRequest) (AdmitPendingToolCompletionResult, bool, error) {
	var result0 AdmitPendingToolCompletionResult
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ReadPendingToolCompletion(ctx, req)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) ReadSubAgentInput(ctx context.Context, inputID string) (SubAgentInputRecord, bool, error) {
	var result0 SubAgentInputRecord
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ReadSubAgentInput(ctx, inputID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) ReadTurnAdmission(ctx context.Context, threadID, turnID, runID string) (AdmitTurnResult, bool, error) {
	var result0 AdmitTurnResult
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ReadTurnAdmission(ctx, threadID, turnID, runID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) RecoverInterruptedTurn(ctx context.Context, req RecoverInterruptedTurnRequest) (RecoverInterruptedTurnResult, error) {
	var result0 RecoverInterruptedTurnResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.RecoverInterruptedTurn(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) RejectEffectAttempt(ctx context.Context, req RejectEffectAttemptRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.RejectEffectAttempt(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReleaseTurnLease(ctx context.Context, proof TurnLease) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.ReleaseTurnLease(ctx, proof)
	})
	return err
}

func (repo *BackendRepo) RenewTurnLease(ctx context.Context, proof TurnLease) (TurnLease, error) {
	var result0 TurnLease
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.RenewTurnLease(ctx, proof)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ResolveApproval(ctx context.Context, req ResolveApprovalRequest) (ResolveApprovalResult, error) {
	var result0 ResolveApprovalResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ResolveApproval(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) SetThreadTitle(ctx context.Context, req SetThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.SetThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) SettlePendingToolRecovery(ctx context.Context, req SettlePendingToolRecoveryRequest) (SettlePendingToolRecoveryResult, error) {
	var result0 SettlePendingToolRecoveryResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.SettlePendingToolRecovery(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) TakeOverCompaction(ctx context.Context, req TakeOverCompactionRequest) (BeginCompactionResult, error) {
	var result0 BeginCompactionResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.TakeOverCompaction(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Thread(ctx context.Context, threadID string) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Thread(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ThreadTombstone(ctx context.Context, threadID string) (ThreadTombstone, error) {
	var result0 ThreadTombstone
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ThreadTombstone(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) UpdateThread(ctx context.Context, meta ThreadMeta) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.UpdateThread(ctx, meta)
	})
	return err
}

func (repo *BackendRepo) ValidateArtifactForkDestination(ctx context.Context, closure artifact.Closure) error {
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		return memory.ValidateArtifactForkDestination(ctx, closure)
	})
	return err
}

func (repo *BackendRepo) ValidateInterruptedTurnResolution(ctx context.Context, req RecoverInterruptedTurnRequest) error {
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		return memory.ValidateInterruptedTurnResolution(ctx, req)
	})
	return err
}
