// Code generated by genbackendrepo; DO NOT EDIT.

package sessiontree

import (
	"context"

	"github.com/floegence/floret/v4/internal/session/artifact"
)

func (repo *BackendRepo) Append(ctx context.Context, entry Entry, opts AppendOptions) (Entry, error) {
	var result0 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Append(ctx, entry, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) AppendRuntimeFacts(ctx context.Context, threadID string, entries []Entry) ([]Entry, error) {
	var result0 []Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.AppendRuntimeFacts(ctx, threadID, entries)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ArtifactClosure(ctx context.Context, req ArtifactClosureRequest) (artifact.Closure, error) {
	var result0 artifact.Closure
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ArtifactClosure(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) BeginAutomaticThreadTitle(ctx context.Context, req BeginAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.BeginAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) BeginEffectDispatch(ctx context.Context, req BeginEffectDispatchRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.BeginEffectDispatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CancelTurn(ctx context.Context, req CancelTurnRequest) (CancelTurnResult, error) {
	var result0 CancelTurnResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CancelTurn(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CanonicalTurnEntries(ctx context.Context, threadID, turnID, runID string) ([]Entry, bool, error) {
	var result0 []Entry
	var result1 bool
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.CanonicalTurnEntries(ctx, threadID, turnID, runID)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) ClaimEffectRetry(ctx context.Context, req ClaimEffectRetryRequest) (ClaimEffectRetryResult, error) {
	var result0 ClaimEffectRetryResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ClaimEffectRetry(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CompareAndSwapAgentTodoState(ctx context.Context, state AgentTodoState, expectedVersion int64) (AgentTodoState, error) {
	var result0 AgentTodoState
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CompareAndSwapAgentTodoState(ctx, state, expectedVersion)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CompleteAutomaticThreadTitle(ctx context.Context, req CompleteAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CompleteAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CreateThread(ctx context.Context, meta ThreadMeta) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.CreateThread(ctx, meta)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) CreateThreadWithInitialEntry(ctx context.Context, meta ThreadMeta, initial Entry) (ThreadMeta, Entry, error) {
	var result0 ThreadMeta
	var result1 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.CreateThreadWithInitialEntry(ctx, meta, initial)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) DeleteProviderState(ctx context.Context, threadID string) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.DeleteProviderState(ctx, threadID)
	})
	return err
}

func (repo *BackendRepo) DeleteRootTree(ctx context.Context, rootThreadID string) (DeleteRootTreeResult, error) {
	var result0 DeleteRootTreeResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.DeleteRootTree(ctx, rootThreadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) DeleteRootTreeWithRequest(ctx context.Context, rootThreadID, requestKey, fingerprint string) (DeleteRootTreeResult, error) {
	var result0 DeleteRootTreeResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.DeleteRootTreeWithRequest(ctx, rootThreadID, requestKey, fingerprint)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) EffectAttempt(ctx context.Context, threadID, attemptID string) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.EffectAttempt(ctx, threadID, attemptID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Entries(ctx context.Context, threadID string) ([]Entry, error) {
	var result0 []Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Entries(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Entry(ctx context.Context, threadID, entryID string) (Entry, error) {
	var result0 Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Entry(ctx, threadID, entryID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FailAutomaticThreadTitle(ctx context.Context, req FailAutomaticThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FailAutomaticThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishEffectDispatch(ctx context.Context, req FinishEffectDispatchRequest) (FinishEffectDispatchResult, error) {
	var result0 FinishEffectDispatchResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishEffectDispatch(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) FinishTurn(ctx context.Context, req FinishTurnRequest) (FinishTurnResult, error) {
	var result0 FinishTurnResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.FinishTurn(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Fork(ctx context.Context, opts ForkOptions) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Fork(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ForkWithInitialEntry(ctx context.Context, opts ForkOptions, initial Entry) (ThreadMeta, Entry, error) {
	var result0 ThreadMeta
	var result1 Entry
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, result1, callErr = memory.ForkWithInitialEntry(ctx, opts, initial)
		return callErr
	})
	return result0, result1, err
}

func (repo *BackendRepo) ListCanonicalTurns(ctx context.Context, opts ListCanonicalTurnsOptions) (CanonicalTurnsPage, error) {
	var result0 CanonicalTurnsPage
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ListCanonicalTurns(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ListThreads(ctx context.Context, opts ListThreadsOptions) ([]ThreadMeta, error) {
	var result0 []ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ListThreads(ctx, opts)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) MarkEffectUnknown(ctx context.Context, req MarkEffectUnknownRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.MarkEffectUnknown(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) MoveLeaf(ctx context.Context, threadID, entryID string) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.MoveLeaf(ctx, threadID, entryID)
	})
	return err
}

func (repo *BackendRepo) Path(ctx context.Context, threadID, leafID string) ([]Entry, error) {
	var result0 []Entry
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Path(ctx, threadID, leafID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PathPage(ctx context.Context, threadID, leafID, beforeEntryID string, limit int) (PathPage, error) {
	var result0 PathPage
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PathPage(ctx, threadID, leafID, beforeEntryID, limit)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PendingAutomaticThreadTitles(ctx context.Context) ([]ThreadMeta, error) {
	var result0 []ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PendingAutomaticThreadTitles(ctx)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PrepareEffectAttempt(ctx context.Context, req PrepareEffectAttemptRequest) (PrepareEffectAttemptResult, error) {
	var result0 PrepareEffectAttemptResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.PrepareEffectAttempt(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ProviderState(ctx context.Context, threadID string) (ProviderStateRecord, error) {
	var result0 ProviderStateRecord
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ProviderState(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) PutProviderState(ctx context.Context, record ProviderStateRecord) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.PutProviderState(ctx, record)
	})
	return err
}

func (repo *BackendRepo) ReadAgentTodoState(ctx context.Context, threadID string) (AgentTodoState, error) {
	var result0 AgentTodoState
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadAgentTodoState(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadArtifact(ctx context.Context, req ArtifactReadRequest) (ArtifactContent, error) {
	var result0 ArtifactContent
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadArtifact(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ReadCanonicalTurn(ctx context.Context, threadID, turnID string) (CanonicalTurnRead, error) {
	var result0 CanonicalTurnRead
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ReadCanonicalTurn(ctx, threadID, turnID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) RejectEffectAttempt(ctx context.Context, req RejectEffectAttemptRequest) (EffectAttempt, error) {
	var result0 EffectAttempt
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.RejectEffectAttempt(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) SetThreadTitle(ctx context.Context, req SetThreadTitleRequest) (ThreadTitleMutationResult, error) {
	var result0 ThreadTitleMutationResult
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.SetThreadTitle(ctx, req)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) Thread(ctx context.Context, threadID string) (ThreadMeta, error) {
	var result0 ThreadMeta
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.Thread(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ThreadOrigin(ctx context.Context, requestKey string) (ThreadOrigin, error) {
	var result0 ThreadOrigin
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ThreadOrigin(ctx, requestKey)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) ThreadTombstone(ctx context.Context, threadID string) (ThreadTombstone, error) {
	var result0 ThreadTombstone
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		var callErr error
		result0, callErr = memory.ThreadTombstone(ctx, threadID)
		return callErr
	})
	return result0, err
}

func (repo *BackendRepo) UpdateThread(ctx context.Context, meta ThreadMeta) error {
	err := repo.update(ctx, func(memory *MemoryRepo) error {
		return memory.UpdateThread(ctx, meta)
	})
	return err
}

func (repo *BackendRepo) ValidateArtifactForkDestination(ctx context.Context, closure artifact.Closure) error {
	err := repo.view(ctx, func(memory *MemoryRepo) error {
		return memory.ValidateArtifactForkDestination(ctx, closure)
	})
	return err
}
