package runtime

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/floegence/floret/config"
	"github.com/floegence/floret/internal/configbridge"
	"github.com/floegence/floret/internal/engine"
	"github.com/floegence/floret/internal/provider"
	"github.com/floegence/floret/internal/provider/adapters"
	"github.com/floegence/floret/internal/session"
	"github.com/floegence/floret/internal/session/compaction"
	"github.com/floegence/floret/observation"
	"github.com/floegence/floret/tools"
)

type ManualCompactionPollRequest struct {
	RunID         RunID         `json:"run_id,omitempty"`
	ThreadID      ThreadID      `json:"thread_id,omitempty"`
	TurnID        TurnID        `json:"turn_id,omitempty"`
	TraceID       TraceID       `json:"trace_id,omitempty"`
	PromptScopeID PromptScopeID `json:"prompt_scope_id,omitempty"`
	Step          int           `json:"step,omitempty"`
}

type ManualCompactionRequest struct {
	RequestID   string    `json:"request_id"`
	Source      string    `json:"source,omitempty"`
	RequestedAt time.Time `json:"requested_at,omitempty"`
}

// ManualCompactionOperationID returns the Floret operation identity that links
// the start, debug, complete, and failed observations for a projected manual
// compaction at the given provider-loop step.
func ManualCompactionOperationID(runID RunID, step int, requestID string) string {
	return engine.CompactionOperationID(string(runID), step, compaction.TriggerManual, compaction.ReasonManual, requestID)
}

type ManualCompactionSource interface {
	PollManualCompaction(context.Context, ManualCompactionPollRequest) (ManualCompactionRequest, bool, error)
}

// ToolSurfaceRequest identifies the run phase asking for the current host tool
// surface. Hosts may use it to refresh tool visibility, hosted tools, prompt
// instructions, and host context between provider requests and tool dispatch.
type ToolSurfaceRequest struct {
	RunID         RunID
	ThreadID      ThreadID
	TurnID        TurnID
	TraceID       TraceID
	PromptScopeID PromptScopeID
	Step          int
	Phase         string
	Labels        RunLabels
	HostContext   map[string]string
}

// ToolSurface is the host-supplied tool view for the current run phase. It is
// product-neutral: hosts own policy names and may project them into tools,
// prompt text, or host context without Floret interpreting them.
type ToolSurface struct {
	Tools                 *tools.Registry
	ToolDefinitions       []tools.ToolDefinition
	HostedToolDefinitions []HostedToolDefinition
	SystemPrompt          string
	HostContext           map[string]string
	Epoch                 string
	Reason                string
}

type ToolSurfaceProvider func(context.Context, ToolSurfaceRequest) (ToolSurface, error)

// ModelGateway lets a host supply model access while Floret still owns the
// agent loop, tool dispatch, context pressure, and runtime ledgers.
type ModelGateway interface {
	StreamModel(context.Context, ModelRequest) (<-chan ModelEvent, error)
}

// ModelGatewayIdentity names the host-owned model transport used by a
// ModelGateway-backed Host.
type ModelGatewayIdentity struct {
	Provider string
	Model    string
}

// ModelRequest is the host-safe model request shape passed to ModelGateway.
type ModelRequest struct {
	RunID           RunID
	ThreadID        ThreadID
	TurnID          TurnID
	TraceID         TraceID
	PromptScopeID   PromptScopeID
	Step            int
	Provider        string
	Model           string
	Messages        []ModelMessage
	Tools           []tools.ToolDefinition
	HostedTools     []HostedToolDefinition
	MaxOutputTokens int64
	Reasoning       ReasoningSelection
	PreviousState   *ModelState
	Labels          RunLabels
}

// ModelMessage is a provider-visible message generated by Floret for a
// ModelGateway request.
type ModelMessage struct {
	Role       string `json:"role"`
	Content    string `json:"content,omitempty"`
	Reasoning  string `json:"reasoning,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	ToolName   string `json:"tool_name,omitempty"`
	ToolArgs   string `json:"tool_args,omitempty"`
}

// ModelState is opaque provider continuation state. Floret carries it through
// the run lifecycle and returns the latest state; hosts and model gateways own
// provider-specific interpretation and cross-turn persistence.
type ModelState struct {
	Kind       string            `json:"kind,omitempty"`
	ID         string            `json:"id,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
}

// ModelEventType is a streamed model event kind.
type ModelEventType string

const (
	ModelEventDelta         ModelEventType = "delta"
	ModelEventReasoning     ModelEventType = "reasoning"
	ModelEventToolCallStart ModelEventType = "tool_call_start"
	ModelEventToolCallDelta ModelEventType = "tool_call_delta"
	ModelEventToolCallEnd   ModelEventType = "tool_call_end"
	ModelEventToolCalls     ModelEventType = "tool_calls"
	ModelEventUsage         ModelEventType = "usage"
	ModelEventSources       ModelEventType = "sources"
	ModelEventDone          ModelEventType = "done"
	ModelEventEmpty         ModelEventType = "empty"
	ModelEventTruncated     ModelEventType = "truncated"
	ModelEventError         ModelEventType = "error"
)

// ModelToolCallStream identifies a tool call while the model is still
// generating it. The final executable tool calls are delivered separately by
// ModelEventToolCalls.
type ModelToolCallStream struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

// ModelEvent carries streamed model output.
type ModelEvent struct {
	Type           ModelEventType       `json:"type"`
	Text           string               `json:"text,omitempty"`
	ToolCallStream *ModelToolCallStream `json:"tool_call_stream,omitempty"`
	ToolCalls      []tools.ToolCall     `json:"tool_calls,omitempty"`
	Sources        []SourceRef          `json:"sources,omitempty"`
	Reason         string               `json:"reason,omitempty"`
	Usage          ProviderUsage        `json:"usage,omitempty"`
	ResponseID     string               `json:"response_id,omitempty"`
	ResponseState  *ModelState          `json:"response_state,omitempty"`
	Err            error                `json:"-"`
}

type SourceRef struct {
	Title string `json:"title,omitempty"`
	URL   string `json:"url,omitempty"`
}

type HostedToolDefinition struct {
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Description string         `json:"description,omitempty"`
	Parameters  map[string]any `json:"parameters,omitempty"`
	Options     map[string]any `json:"options,omitempty"`
}

// RunMetrics summarizes the observable work completed by a run.
type RunMetrics struct {
	ProviderUsage ProviderUsage `json:"provider_usage"`
	Steps         int           `json:"steps"`
	LLMRequests   int           `json:"llm_requests"`
	ToolCalls     int           `json:"tool_calls"`
	Compactions   int           `json:"compactions"`
	Retries       int           `json:"retries"`
	WallTimeMS    int64         `json:"wall_time_ms,omitempty"`
}

// ProviderUsage is normalized provider token and cost usage.
type ProviderUsage struct {
	InputTokens       int64   `json:"input_tokens,omitempty"`
	OutputTokens      int64   `json:"output_tokens,omitempty"`
	ReasoningTokens   int64   `json:"reasoning_tokens,omitempty"`
	CacheReadTokens   int64   `json:"cache_read_tokens,omitempty"`
	CacheWriteTokens  int64   `json:"cache_write_tokens,omitempty"`
	TotalTokens       int64   `json:"total_tokens,omitempty"`
	CostUSD           float64 `json:"cost_usd,omitempty"`
	Source            string  `json:"source,omitempty"`
	Available         bool    `json:"available,omitempty"`
	WindowInputTokens int64   `json:"window_input_tokens,omitempty"`
}

// TurnCompletionPolicy controls how the provider loop may finish. The zero
// value uses natural stops.
type TurnCompletionPolicy string

const (
	// TurnCompletionNaturalStop lets the provider's natural stop finish the run.
	TurnCompletionNaturalStop TurnCompletionPolicy = "natural_stop"
	// TurnCompletionExplicitSignal requires a projected turn signal to finish or
	// pause the run.
	TurnCompletionExplicitSignal TurnCompletionPolicy = "explicit_signal"
)

// TurnLimits contains per-run budget and continuation caps.
type TurnLimits struct {
	MaxTotalTokens           int64
	MaxCostUSD               float64
	MaxToolCalls             int
	MaxLengthContinuations   int
	MaxStopHookContinuations int
}

// SignalDisposition describes how a projected turn signal affects the run.
type SignalDisposition string

const (
	// SignalContinue returns a provider-visible tool result and continues.
	SignalContinue SignalDisposition = "continue"
	// SignalWaiting pauses the run for host or user input.
	SignalWaiting SignalDisposition = "waiting"
	// SignalTerminal completes the run with the projected signal.
	SignalTerminal SignalDisposition = "terminal"
)

// TurnSignal is a host-safe projection of a signal tool call.
type TurnSignal struct {
	Disposition SignalDisposition                 `json:"disposition"`
	Name        string                            `json:"name"`
	CallID      string                            `json:"call_id,omitempty"`
	Payload     map[string]any                    `json:"payload,omitempty"`
	Activity    *observation.ActivityPresentation `json:"activity,omitempty"`
	OutputText  string                            `json:"output_text,omitempty"`
	ArgsHash    string                            `json:"args_hash,omitempty"`
	Labels      map[string]string                 `json:"labels,omitempty"`
}

// TurnSignalSpec lets a host declare provider-visible signal tools without
// importing Floret implementation packages.
type TurnSignalSpec struct {
	Definitions []tools.ToolDefinition
	Project     func(tools.ToolCall) (TurnSignal, bool, error)
}

type manualCompactionSourceAdapter struct {
	source ManualCompactionSource
}

func projectedManualCompactionSource(source ManualCompactionSource) engine.ManualCompactionSource {
	if source == nil {
		return nil
	}
	return manualCompactionSourceAdapter{source: source}
}

func (s manualCompactionSourceAdapter) PollManualCompaction(ctx context.Context, req engine.ManualCompactionPollRequest) (engine.ManualCompactionRequest, bool, error) {
	if s.source == nil {
		return engine.ManualCompactionRequest{}, false, nil
	}
	manual, ok, err := s.source.PollManualCompaction(ctx, ManualCompactionPollRequest{
		RunID:         RunID(req.RunID),
		ThreadID:      ThreadID(req.ThreadID),
		TurnID:        TurnID(req.TurnID),
		TraceID:       TraceID(req.TraceID),
		PromptScopeID: PromptScopeID(req.PromptScopeID),
		Step:          req.Step,
	})
	if err != nil || !ok {
		return engine.ManualCompactionRequest{}, ok, err
	}
	return engineManualCompactionRequest(manual), true, nil
}

func engineManualCompactionRequest(manual ManualCompactionRequest) engine.ManualCompactionRequest {
	return engine.ManualCompactionRequest{
		RequestID: strings.TrimSpace(manual.RequestID),
		Source:    strings.TrimSpace(manual.Source),
	}
}

func projectedModelProvider(cfg config.Config, gateway ModelGateway, identity ModelGatewayIdentity) (provider.Provider, error) {
	if gateway != nil {
		return modelGatewayProvider{gateway: gateway, identity: identity}, nil
	}
	return adapters.NewProvider(cfg)
}

func resolveModelGatewayHostConfig(cfg config.Config, identity ModelGatewayIdentity) (config.Config, error) {
	identity, err := normalizeModelGatewayIdentity(identity)
	if err != nil {
		return config.Config{}, err
	}
	if strings.TrimSpace(cfg.Provider) != "" ||
		strings.TrimSpace(cfg.Model) != "" ||
		strings.TrimSpace(cfg.BaseURL) != "" ||
		strings.TrimSpace(cfg.APIKey) != "" ||
		strings.TrimSpace(cfg.FakeResponse) != "" {
		return config.Config{}, errors.New("model gateway host config must not set provider transport fields")
	}
	if cfg.ContextPolicy.ContextWindowTokens <= 0 {
		return config.Config{}, errors.New("model gateway host config requires context policy context window tokens")
	}
	cfg.Provider = identity.Provider
	cfg.Model = identity.Model
	resolved, err := resolveProviderFreeModelGatewayConfig(cfg)
	if err != nil {
		return config.Config{}, err
	}
	return resolved, nil
}

func resolveProviderFreeModelGatewayConfig(cfg config.Config) (config.Config, error) {
	if cfg.SkillPromptBudgetBytes <= 0 {
		cfg.SkillPromptBudgetBytes = 16 * 1024
	}
	cfg.Reasoning = config.NormalizeReasoningSelection(cfg.Reasoning)
	if _, err := config.PromptCacheRetention(cfg); err != nil {
		return config.Config{}, err
	}
	if !config.ValidateReasoningLevel(cfg.Reasoning.Level) {
		return config.Config{}, fmt.Errorf("unsupported reasoning level %q", cfg.Reasoning.Level)
	}
	cfg.ContextPolicy = configbridge.NormalizeContextPolicy(cfg.ContextPolicy)
	return config.ResolvePrompt(cfg), nil
}

func normalizeModelGatewayIdentity(identity ModelGatewayIdentity) (ModelGatewayIdentity, error) {
	identity.Provider = strings.TrimSpace(identity.Provider)
	identity.Model = strings.TrimSpace(identity.Model)
	if identity.Provider == "" {
		return ModelGatewayIdentity{}, errors.New("model gateway identity provider is required")
	}
	if identity.Model == "" {
		return ModelGatewayIdentity{}, errors.New("model gateway identity model is required")
	}
	return identity, nil
}

func projectedReasoningSelection(requested ReasoningSelection, fallback ReasoningSelection) provider.ReasoningSelection {
	requested = config.NormalizeReasoningSelection(requested)
	if !requested.IsZero() {
		return configbridge.ReasoningSelection(requested)
	}
	return configbridge.ReasoningSelection(fallback)
}

type modelGatewayProvider struct {
	gateway  ModelGateway
	identity ModelGatewayIdentity
}

func (p modelGatewayProvider) Stream(ctx context.Context, req provider.Request) (<-chan provider.StreamEvent, error) {
	if p.gateway == nil {
		return nil, errors.New("model gateway is required")
	}
	stream, err := p.gateway.StreamModel(ctx, ModelRequest{
		RunID:           RunID(req.RunID),
		ThreadID:        ThreadID(req.ThreadID),
		TurnID:          TurnID(req.TurnID),
		TraceID:         TraceID(req.TraceID),
		PromptScopeID:   PromptScopeID(req.PromptScopeID),
		Step:            req.Step,
		Provider:        p.identity.Provider,
		Model:           p.identity.Model,
		Messages:        runtimeModelMessages(req.Messages),
		Tools:           runtimeToolDefinitions(req.Tools),
		HostedTools:     runtimeHostedToolDefinitions(req.HostedTools),
		MaxOutputTokens: req.MaxOutputTokens,
		Reasoning:       configbridge.PublicReasoningSelection(req.Reasoning),
		PreviousState:   modelState(req.PreviousState),
		Labels:          providerRequestLabels(req.Labels),
	})
	if err != nil {
		return nil, err
	}
	out := make(chan provider.StreamEvent)
	go func() {
		defer close(out)
		for ev := range stream {
			select {
			case <-ctx.Done():
				return
			case out <- providerStreamEvent(ev):
			}
		}
	}()
	return out, nil
}

func runtimeModelMessages(messages []session.Message) []ModelMessage {
	out := make([]ModelMessage, 0, len(messages))
	for _, msg := range messages {
		out = append(out, ModelMessage{
			Role:       string(msg.Role),
			Content:    msg.Content,
			Reasoning:  msg.Reasoning,
			ToolCallID: msg.ToolCallID,
			ToolName:   msg.ToolName,
			ToolArgs:   msg.ToolArgs,
		})
	}
	return out
}

func runtimeToolDefinitions(defs []provider.ToolDefinition) []tools.ToolDefinition {
	out := make([]tools.ToolDefinition, 0, len(defs))
	for _, def := range defs {
		out = append(out, tools.ToolDefinition{
			Name:         def.Name,
			Title:        def.Title,
			Description:  def.Description,
			InputSchema:  cloneAnyMap(def.InputSchema),
			OutputSchema: cloneAnyMap(def.OutputSchema),
			Strict:       def.Strict,
			Annotations:  cloneAnyMap(def.Annotations),
		})
	}
	return out
}

func runtimeHostedToolDefinitions(defs []provider.HostedToolDefinition) []HostedToolDefinition {
	out := make([]HostedToolDefinition, 0, len(defs))
	for _, def := range defs {
		out = append(out, HostedToolDefinition{
			Name:        def.Name,
			Type:        def.Type,
			Description: def.Description,
			Parameters:  cloneAnyMap(def.Parameters),
			Options:     cloneAnyMap(def.Options),
		})
	}
	return out
}

func providerStreamEvent(ev ModelEvent) provider.StreamEvent {
	return provider.StreamEvent{
		Type:           provider.EventType(ev.Type),
		Text:           ev.Text,
		ToolCallStream: providerToolCallStream(ev.ToolCallStream),
		ToolCalls:      providerToolCalls(ev.ToolCalls),
		Sources:        providerSourceRefs(ev.Sources),
		Reason:         ev.Reason,
		Usage:          providerUsage(ev.Usage),
		ResponseID:     ev.ResponseID,
		ResponseState:  providerState(ev.ResponseState),
		Err:            ev.Err,
	}
}

func providerToolCallStream(call *ModelToolCallStream) provider.ToolCallStream {
	if call == nil {
		return provider.ToolCallStream{}
	}
	return provider.ToolCallStream{
		ID:   call.ID,
		Name: call.Name,
	}
}

func providerToolCalls(calls []tools.ToolCall) []provider.ToolCall {
	out := make([]provider.ToolCall, 0, len(calls))
	for _, call := range calls {
		out = append(out, providerToolCall(call))
	}
	return out
}

func providerSourceRefs(in []SourceRef) []provider.SourceRef {
	out := make([]provider.SourceRef, 0, len(in))
	for _, ref := range in {
		if strings.TrimSpace(ref.Title) == "" && strings.TrimSpace(ref.URL) == "" {
			continue
		}
		out = append(out, provider.SourceRef{
			Title: strings.TrimSpace(ref.Title),
			URL:   strings.TrimSpace(ref.URL),
		})
	}
	return out
}

func providerToolCall(call tools.ToolCall) provider.ToolCall {
	return provider.ToolCall{
		ID:        call.ID,
		Name:      call.Name,
		Args:      call.Args,
		Reasoning: call.Reasoning,
	}
}

func modelState(in *provider.State) *ModelState {
	if in == nil {
		return nil
	}
	return &ModelState{
		Kind:       in.Kind,
		ID:         in.ID,
		Attributes: cloneStringMap(in.Attributes),
	}
}

func providerState(in *ModelState) *provider.State {
	if in == nil {
		return nil
	}
	return &provider.State{
		Kind:       in.Kind,
		ID:         in.ID,
		Attributes: cloneStringMap(in.Attributes),
	}
}

func agentHarnessSupplementalContext(in []TurnSupplementalContextItem) []engine.TurnSupplementalContextItem {
	if len(in) == 0 {
		return nil
	}
	out := make([]engine.TurnSupplementalContextItem, 0, len(in))
	for _, item := range in {
		out = append(out, engine.TurnSupplementalContextItem{
			Kind:      item.Kind,
			Title:     item.Title,
			Text:      item.Text,
			Metadata:  cloneStringMap(item.Metadata),
			Sensitive: item.Sensitive,
			Truncated: item.Truncated,
		})
	}
	return out
}

func providerUsage(in ProviderUsage) provider.Usage {
	return provider.Usage{
		InputTokens:       in.InputTokens,
		OutputTokens:      in.OutputTokens,
		ReasoningTokens:   in.ReasoningTokens,
		CacheReadTokens:   in.CacheReadTokens,
		CacheWriteTokens:  in.CacheWriteTokens,
		TotalTokens:       in.TotalTokens,
		CostUSD:           in.CostUSD,
		Source:            provider.UsageSource(in.Source),
		Available:         in.Available,
		WindowInputTokens: in.WindowInputTokens,
	}
}

func runtimeMetrics(in engine.RunMetrics) RunMetrics {
	return RunMetrics{
		ProviderUsage: runtimeProviderUsage(in.Usage),
		Steps:         in.Steps,
		LLMRequests:   in.LLMRequests,
		ToolCalls:     in.ToolCalls,
		Compactions:   in.Compactions,
		Retries:       in.Retries,
		WallTimeMS:    in.WallTimeMS,
	}
}

func runtimeProviderUsage(in provider.Usage) ProviderUsage {
	in = in.Normalized()
	return ProviderUsage{
		InputTokens:       in.InputTokens,
		OutputTokens:      in.OutputTokens,
		ReasoningTokens:   in.ReasoningTokens,
		CacheReadTokens:   in.CacheReadTokens,
		CacheWriteTokens:  in.CacheWriteTokens,
		TotalTokens:       in.TotalTokens,
		CostUSD:           in.CostUSD,
		Source:            string(in.Source),
		Available:         in.Available,
		WindowInputTokens: in.WindowInputTokens,
	}
}

func runtimeTurnSignal(in *engine.ControlSignal) *TurnSignal {
	if in == nil {
		return nil
	}
	return &TurnSignal{
		Disposition: SignalDisposition(in.Disposition),
		Name:        in.Name,
		CallID:      in.CallID,
		Payload:     cloneAnyMap(in.Payload),
		Activity:    cloneActivityPresentation(in.Activity),
		OutputText:  in.OutputText,
		ArgsHash:    in.ArgsHash,
		Labels:      cloneStringMap(in.Labels),
	}
}

func engineLabels(in RunLabels) engine.RunLabels {
	return engine.RunLabels{
		Correlation: cloneStringMap(in.Correlation),
		Host:        cloneStringMap(in.Host),
	}
}

func providerRequestLabels(in provider.RequestLabels) RunLabels {
	return RunLabels{
		Correlation: cloneStringMap(in.Correlation),
		Host:        cloneStringMap(in.Host),
	}
}

func runtimeToolSurfaceProvider(provider ToolSurfaceProvider) engine.ToolSurfaceProvider {
	if provider == nil {
		return nil
	}
	return func(ctx context.Context, req engine.ToolSurfaceRequest) (engine.ToolSurface, error) {
		surface, err := provider(ctx, ToolSurfaceRequest{
			RunID:         RunID(req.RunID),
			ThreadID:      ThreadID(req.ThreadID),
			TurnID:        TurnID(req.TurnID),
			TraceID:       TraceID(req.TraceID),
			PromptScopeID: PromptScopeID(req.PromptScopeID),
			Step:          req.Step,
			Phase:         strings.TrimSpace(req.Phase),
			Labels:        publicRunLabels(req.Labels),
			HostContext:   cloneStringMap(req.HostContext),
		})
		if err != nil {
			return engine.ToolSurface{}, err
		}
		return engine.ToolSurface{
			Tools:                 surface.Tools,
			ToolDefinitions:       providerToolDefinitionsFromRuntime(surface.ToolDefinitions),
			HostedToolDefinitions: providerHostedToolDefinitions(surface.HostedToolDefinitions),
			SystemPrompt:          surface.SystemPrompt,
			HostContext:           cloneStringMap(surface.HostContext),
			Epoch:                 strings.TrimSpace(surface.Epoch),
			Reason:                strings.TrimSpace(surface.Reason),
		}, nil
	}
}

func publicRunLabels(in engine.RunLabels) RunLabels {
	return RunLabels{
		Correlation: cloneStringMap(in.Correlation),
		Host:        cloneStringMap(in.Host),
	}
}

func providerToolDefinitionsFromRuntime(defs []tools.ToolDefinition) []provider.ToolDefinition {
	if defs == nil {
		return nil
	}
	out := make([]provider.ToolDefinition, 0, len(defs))
	for _, def := range defs {
		name := strings.TrimSpace(def.Name)
		if name == "" {
			continue
		}
		out = append(out, provider.ToolDefinition{
			Name:         name,
			Title:        strings.TrimSpace(def.Title),
			Description:  strings.TrimSpace(def.Description),
			InputSchema:  cloneAnyMap(def.InputSchema),
			OutputSchema: cloneAnyMap(def.OutputSchema),
			Strict:       def.Strict,
			Annotations:  cloneAnyMap(def.Annotations),
		})
	}
	return out
}

func providerHostedToolDefinitions(defs []HostedToolDefinition) []provider.HostedToolDefinition {
	if defs == nil {
		return nil
	}
	out := make([]provider.HostedToolDefinition, 0, len(defs))
	for _, def := range defs {
		typ := strings.TrimSpace(def.Type)
		if typ == "" {
			continue
		}
		out = append(out, provider.HostedToolDefinition{
			Name:        strings.TrimSpace(def.Name),
			Type:        typ,
			Description: strings.TrimSpace(def.Description),
			Parameters:  cloneAnyMap(def.Parameters),
			Options:     cloneAnyMap(def.Options),
		})
	}
	return out
}

func engineTurnCompletionPolicy(policy TurnCompletionPolicy) (engine.CompletionPolicy, error) {
	switch policy {
	case "":
		return engine.CompletionNaturalStop, nil
	case TurnCompletionNaturalStop:
		return engine.CompletionNaturalStop, nil
	case TurnCompletionExplicitSignal:
		return engine.CompletionExplicitSignal, nil
	default:
		return "", fmt.Errorf("unsupported completion policy %q", policy)
	}
}

func engineTurnSignalSpec(spec TurnSignalSpec, policy engine.CompletionPolicy) (engine.ControlSpec, error) {
	if len(spec.Definitions) == 0 && spec.Project == nil {
		if policy == engine.CompletionExplicitSignal {
			return engine.ControlSpec{}, errors.New("signal spec is required when completion policy is explicit_signal")
		}
		return engine.ControlSpec{
			Definitions: []provider.ToolDefinition{},
			Project: func(provider.ToolCall) (engine.ControlSignal, bool, error) {
				return engine.ControlSignal{}, false, nil
			},
		}, nil
	}
	out := engine.ControlSpec{
		Definitions: make([]provider.ToolDefinition, 0, len(spec.Definitions)),
	}
	for _, def := range spec.Definitions {
		name := strings.TrimSpace(def.Name)
		if name == "" {
			continue
		}
		out.Definitions = append(out.Definitions, provider.ToolDefinition{
			Name:         name,
			Title:        strings.TrimSpace(def.Title),
			Description:  strings.TrimSpace(def.Description),
			InputSchema:  cloneAnyMap(def.InputSchema),
			OutputSchema: cloneAnyMap(def.OutputSchema),
			Strict:       def.Strict,
			Annotations:  cloneAnyMap(def.Annotations),
		})
	}
	if spec.Project != nil {
		out.Project = func(call provider.ToolCall) (engine.ControlSignal, bool, error) {
			signal, ok, err := spec.Project(tools.ToolCall{
				ID:        call.ID,
				Name:      call.Name,
				Args:      call.Args,
				Reasoning: call.Reasoning,
			})
			if err != nil || !ok {
				return engine.ControlSignal{}, ok, err
			}
			return engine.ControlSignal{
				Disposition: engine.ControlDisposition(signal.Disposition),
				Name:        signal.Name,
				CallID:      signal.CallID,
				Payload:     cloneAnyMap(signal.Payload),
				Activity:    cloneActivityPresentation(signal.Activity),
				OutputText:  signal.OutputText,
				ArgsHash:    signal.ArgsHash,
				Labels:      cloneStringMap(signal.Labels),
			}, true, nil
		}
	}
	if len(out.Definitions) == 0 {
		return engine.ControlSpec{}, errors.New("signal spec must include at least one named definition")
	}
	if out.Project == nil {
		return engine.ControlSpec{}, errors.New("signal spec projector is required")
	}
	return out, nil
}

func cloneAnyMap(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	out := make(map[string]any, len(in))
	for key, value := range in {
		out[key] = cloneAny(value)
	}
	return out
}

func cloneAny(value any) any {
	switch v := value.(type) {
	case map[string]any:
		return cloneAnyMap(v)
	case []any:
		out := make([]any, len(v))
		for i, item := range v {
			out[i] = cloneAny(item)
		}
		return out
	case []string:
		out := []string{}
		if len(v) > 0 {
			out = append(out, v...)
		}
		return out
	case map[string]string:
		return cloneStringMap(v)
	default:
		return value
	}
}
