package runtime

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/floegence/floret/config"
	"github.com/floegence/floret/internal/configbridge"
	"github.com/floegence/floret/internal/engine"
	"github.com/floegence/floret/internal/provider"
	"github.com/floegence/floret/internal/provider/adapters"
	"github.com/floegence/floret/internal/session"
	"github.com/floegence/floret/tools"
)

// ProjectedTurnOptions configures one Floret-managed run over a host-owned
// transcript projection.
type ProjectedTurnOptions struct {
	Config       config.Config
	ModelGateway ModelGateway
	Store        *Store
	Tools        *tools.Registry
	Approver     tools.Approver
	Sink         EventSink
	LoopLimits   LoopLimits
	Capabilities CapabilityOptions
}

// ProjectedTurnRequest is the provider-visible transcript projection for one
// run. Execution identity fields are required and are not inferred from each
// other.
type ProjectedTurnRequest struct {
	RunID                 RunID
	ThreadID              ThreadID
	TurnID                TurnID
	TraceID               TraceID
	PromptScopeID         PromptScopeID
	History               []TranscriptMessage
	Labels                RunLabels
	PreviousProviderState *ModelState
	Completion            TurnCompletionPolicy
	Signals               TurnSignalSpec
	Limits                TurnLimits
}

// ProjectedTurnResult is the host-safe outcome of RunProjectedTurn.
type ProjectedTurnResult struct {
	RunID              RunID               `json:"run_id,omitempty"`
	ThreadID           ThreadID            `json:"thread_id,omitempty"`
	TurnID             TurnID              `json:"turn_id,omitempty"`
	Status             TurnStatus          `json:"status"`
	Output             string              `json:"output,omitempty"`
	Error              string              `json:"error,omitempty"`
	Metrics            RunMetrics          `json:"metrics"`
	Transcript         []TranscriptMessage `json:"transcript,omitempty"`
	CompletionReason   string              `json:"completion_reason,omitempty"`
	ContinuationReason string              `json:"continuation_reason,omitempty"`
	FinishReason       string              `json:"finish_reason,omitempty"`
	RawFinishReason    string              `json:"raw_finish_reason,omitempty"`
	FinishInferred     bool                `json:"finish_inferred,omitempty"`
	Signal             *TurnSignal         `json:"signal,omitempty"`
}

// TranscriptMessage is the small message shape accepted by RunProjectedTurn.
// Supported roles are user, assistant, and tool. System instructions belong in
// config.Config rather than host-projected transcript history.
type TranscriptMessage struct {
	Role       string `json:"role"`
	Content    string `json:"content,omitempty"`
	Reasoning  string `json:"reasoning,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	ToolName   string `json:"tool_name,omitempty"`
	ToolArgs   string `json:"tool_args,omitempty"`
}

// ModelGateway lets a host supply model access while Floret still owns the
// agent loop, tool dispatch, context pressure, and runtime ledgers.
type ModelGateway interface {
	StreamModel(context.Context, ModelRequest) (<-chan ModelEvent, error)
}

// ModelRequest is the host-safe model request shape passed to ModelGateway.
type ModelRequest struct {
	RunID            RunID
	ThreadID         ThreadID
	TurnID           TurnID
	TraceID          TraceID
	PromptScopeID    PromptScopeID
	Step             int
	Provider         string
	Model            string
	Messages         []ModelMessage
	Tools            []tools.ToolDefinition
	MaxOutputTokens  int64
	DisableReasoning bool
	PreviousState    *ModelState
	Labels           RunLabels
}

// ModelMessage is a provider-visible message generated by Floret for a
// ModelGateway request.
type ModelMessage struct {
	Role       string `json:"role"`
	Content    string `json:"content,omitempty"`
	Reasoning  string `json:"reasoning,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`
	ToolName   string `json:"tool_name,omitempty"`
	ToolArgs   string `json:"tool_args,omitempty"`
}

// ModelState is opaque model continuation state owned by Floret runtime data.
type ModelState struct {
	Kind       string            `json:"kind,omitempty"`
	ID         string            `json:"id,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
}

// ModelEventType is a streamed model event kind.
type ModelEventType string

const (
	ModelEventDelta     ModelEventType = "delta"
	ModelEventReasoning ModelEventType = "reasoning"
	ModelEventToolCalls ModelEventType = "tool_calls"
	ModelEventUsage     ModelEventType = "usage"
	ModelEventDone      ModelEventType = "done"
	ModelEventEmpty     ModelEventType = "empty"
	ModelEventTruncated ModelEventType = "truncated"
	ModelEventError     ModelEventType = "error"
)

// ModelEvent carries streamed model output.
type ModelEvent struct {
	Type          ModelEventType   `json:"type"`
	Text          string           `json:"text,omitempty"`
	ToolCalls     []tools.ToolCall `json:"tool_calls,omitempty"`
	Reason        string           `json:"reason,omitempty"`
	Usage         ProviderUsage    `json:"usage,omitempty"`
	ResponseID    string           `json:"response_id,omitempty"`
	ResponseState *ModelState      `json:"response_state,omitempty"`
	Err           error            `json:"-"`
}

// RunMetrics summarizes the observable work completed by a run.
type RunMetrics struct {
	ProviderUsage ProviderUsage `json:"provider_usage"`
	Steps         int           `json:"steps"`
	LLMRequests   int           `json:"llm_requests"`
	ToolCalls     int           `json:"tool_calls"`
	Compactions   int           `json:"compactions"`
	Retries       int           `json:"retries"`
	WallTimeMS    int64         `json:"wall_time_ms,omitempty"`
}

// ProviderUsage is normalized provider token and cost usage.
type ProviderUsage struct {
	InputTokens       int64   `json:"input_tokens,omitempty"`
	OutputTokens      int64   `json:"output_tokens,omitempty"`
	ReasoningTokens   int64   `json:"reasoning_tokens,omitempty"`
	CacheReadTokens   int64   `json:"cache_read_tokens,omitempty"`
	CacheWriteTokens  int64   `json:"cache_write_tokens,omitempty"`
	TotalTokens       int64   `json:"total_tokens,omitempty"`
	CostUSD           float64 `json:"cost_usd,omitempty"`
	Source            string  `json:"source,omitempty"`
	Available         bool    `json:"available,omitempty"`
	WindowInputTokens int64   `json:"window_input_tokens,omitempty"`
}

// TurnCompletionPolicy controls how the provider loop may finish. The zero
// value uses natural stops.
type TurnCompletionPolicy string

const (
	// TurnCompletionNaturalStop lets the provider's natural stop finish the run.
	TurnCompletionNaturalStop TurnCompletionPolicy = "natural_stop"
	// TurnCompletionExplicitSignal requires a projected turn signal to finish or
	// pause the run.
	TurnCompletionExplicitSignal TurnCompletionPolicy = "explicit_signal"
)

// TurnLimits contains per-run budget and continuation caps.
type TurnLimits struct {
	MaxTotalTokens           int64
	MaxCostUSD               float64
	MaxToolCalls             int
	MaxLengthContinuations   int
	MaxStopHookContinuations int
}

// SignalDisposition describes how a projected turn signal affects the run.
type SignalDisposition string

const (
	// SignalContinue returns a provider-visible tool result and continues.
	SignalContinue SignalDisposition = "continue"
	// SignalWaiting pauses the run for host or user input.
	SignalWaiting SignalDisposition = "waiting"
	// SignalTerminal completes the run with the projected signal.
	SignalTerminal SignalDisposition = "terminal"
)

// TurnSignal is a host-safe projection of a signal tool call.
type TurnSignal struct {
	Disposition SignalDisposition `json:"disposition"`
	Name        string            `json:"name"`
	CallID      string            `json:"call_id,omitempty"`
	Payload     map[string]any    `json:"payload,omitempty"`
	OutputText  string            `json:"output_text,omitempty"`
	ArgsHash    string            `json:"args_hash,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
}

// TurnSignalSpec lets a host declare provider-visible signal tools without
// importing Floret implementation packages.
type TurnSignalSpec struct {
	Definitions []tools.ToolDefinition
	Project     func(tools.ToolCall) (TurnSignal, bool, error)
}

// RunProjectedTurn executes one Floret-managed provider loop over a transcript
// supplied by the host.
//
// Use this when the product owns durable conversation rows and Floret owns the
// turn execution, prompt scope, provider ledger, tool dispatch, and observable
// runtime events. Use Host for Floret-managed durable conversations.
func RunProjectedTurn(ctx context.Context, opts ProjectedTurnOptions, req ProjectedTurnRequest) (ProjectedTurnResult, error) {
	cfg, err := config.Resolve(opts.Config, nil)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	ids, err := projectedTurnIdentity(req)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	completionPolicy, err := engineTurnCompletionPolicy(req.Completion)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	signalSpec, err := engineTurnSignalSpec(req.Signals, completionPolicy)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	modelProvider, err := projectedModelProvider(cfg, opts.ModelGateway)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	store := opts.Store
	if store == nil {
		store = NewMemoryStore()
	}
	if err := store.validate(); err != nil {
		return ProjectedTurnResult{}, err
	}
	registry := opts.Tools
	if registry == nil {
		registry = tools.NewRegistry()
	}
	sink := runtimeEventSink{sink: opts.Sink}
	capabilities := mergeCapabilityOptions(cfg, opts.Capabilities)
	effectivePrompt, err := applyCapabilities(registry, cfg.SystemPrompt, capabilities, sink)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	cacheRetention, err := config.PromptCacheRetention(cfg)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	history, err := projectedHistory(req.History)
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	previousProviderState := providerState(req.PreviousProviderState)
	loopLimits := projectedLoopLimits(cfg, opts.LoopLimits, req.Limits)
	eng, err := engine.New(engine.Config{
		Provider:     modelProvider,
		Store:        session.NewMemoryStore(),
		Prompt:       store.prompt,
		Artifacts:    store.artifacts,
		SystemPrompt: effectivePrompt,
		Tools:        registry,
		Sink:         sink,
		Approver:     opts.Approver,
		Options: engine.Options{
			RunID:                    ids.runID,
			ThreadID:                 ids.threadID,
			TurnID:                   ids.turnID,
			TraceID:                  ids.traceID,
			PromptScopeID:            ids.promptScopeID,
			ProviderName:             cfg.Provider,
			Model:                    cfg.Model,
			Labels:                   engineLabels(req.Labels),
			CacheRetention:           configbridge.CacheRetention(cacheRetention),
			ContextPolicy:            configbridge.ContextPolicy(cfg.ContextPolicy),
			MaxEmptyProviderRetries:  loopLimits.MaxEmptyProviderRetries,
			NoProgressLimit:          loopLimits.NoProgressLimit,
			DuplicateToolLimit:       loopLimits.DuplicateToolLimit,
			WallTime:                 loopLimits.WallTime,
			MaxTotalTokens:           loopLimits.MaxTotalTokens,
			MaxCostUSD:               loopLimits.MaxCostUSD,
			MaxToolCalls:             loopLimits.MaxToolCalls,
			MaxLengthContinuations:   loopLimits.MaxLengthContinuations,
			MaxStopHookContinuations: loopLimits.MaxStopHookContinuations,
			CompletionPolicy:         completionPolicy,
			ControlSpec:              signalSpec,
			PreviousProviderState:    previousProviderState,
		},
	})
	if err != nil {
		return ProjectedTurnResult{}, err
	}
	result := eng.RunTurn(ctx, engine.RunInput{
		RunID:                 ids.runID,
		ThreadID:              ids.threadID,
		TurnID:                ids.turnID,
		TraceID:               ids.traceID,
		PromptScopeID:         ids.promptScopeID,
		Labels:                engineLabels(req.Labels),
		PreviousProviderState: previousProviderState,
		History:               history,
	})
	return projectedTurnResult(ids, result), result.Err
}

func projectedModelProvider(cfg config.Config, gateway ModelGateway) (provider.Provider, error) {
	if gateway != nil {
		return modelGatewayProvider{gateway: gateway}, nil
	}
	return adapters.NewProvider(cfg)
}

type modelGatewayProvider struct {
	gateway ModelGateway
}

func (p modelGatewayProvider) Stream(ctx context.Context, req provider.Request) (<-chan provider.StreamEvent, error) {
	if p.gateway == nil {
		return nil, errors.New("model gateway is required")
	}
	stream, err := p.gateway.StreamModel(ctx, ModelRequest{
		RunID:            RunID(req.RunID),
		ThreadID:         ThreadID(req.ThreadID),
		TurnID:           TurnID(req.TurnID),
		TraceID:          TraceID(req.TraceID),
		PromptScopeID:    PromptScopeID(req.PromptScopeID),
		Step:             req.Step,
		Provider:         req.Provider,
		Model:            req.Model,
		Messages:         runtimeModelMessages(req.Messages),
		Tools:            runtimeToolDefinitions(req.Tools),
		MaxOutputTokens:  req.MaxOutputTokens,
		DisableReasoning: req.DisableReasoning,
		PreviousState:    modelState(req.PreviousState),
		Labels:           providerRequestLabels(req.Labels),
	})
	if err != nil {
		return nil, err
	}
	out := make(chan provider.StreamEvent)
	go func() {
		defer close(out)
		for ev := range stream {
			select {
			case <-ctx.Done():
				return
			case out <- providerStreamEvent(ev):
			}
		}
	}()
	return out, nil
}

type projectedIDs struct {
	runID         string
	threadID      string
	turnID        string
	traceID       string
	promptScopeID string
}

type projectedLimits struct {
	MaxEmptyProviderRetries  int
	NoProgressLimit          int
	DuplicateToolLimit       int
	WallTime                 time.Duration
	MaxTotalTokens           int64
	MaxCostUSD               float64
	MaxToolCalls             int
	MaxLengthContinuations   int
	MaxStopHookContinuations int
}

func projectedTurnIdentity(req ProjectedTurnRequest) (projectedIDs, error) {
	runID := strings.TrimSpace(string(req.RunID))
	threadID := strings.TrimSpace(string(req.ThreadID))
	turnID := strings.TrimSpace(string(req.TurnID))
	traceID := strings.TrimSpace(string(req.TraceID))
	promptScopeID := strings.TrimSpace(string(req.PromptScopeID))
	switch {
	case runID == "":
		return projectedIDs{}, errors.New("run id is required")
	case threadID == "":
		return projectedIDs{}, errors.New("thread id is required")
	case turnID == "":
		return projectedIDs{}, errors.New("turn id is required")
	case traceID == "":
		return projectedIDs{}, errors.New("trace id is required")
	case promptScopeID == "":
		return projectedIDs{}, errors.New("prompt scope id is required")
	}
	return projectedIDs{
		runID:         runID,
		threadID:      threadID,
		turnID:        turnID,
		traceID:       traceID,
		promptScopeID: promptScopeID,
	}, nil
}

func projectedLoopLimits(cfg config.Config, opts LoopLimits, req TurnLimits) projectedLimits {
	out := projectedLimits{
		MaxEmptyProviderRetries: cfg.MaxEmptyProviderRetries,
		NoProgressLimit:         cfg.NoProgressLimit,
		DuplicateToolLimit:      cfg.DuplicateToolLimit,
		WallTime:                cfg.WallTime,
	}
	if opts.MaxEmptyProviderRetries > 0 {
		out.MaxEmptyProviderRetries = opts.MaxEmptyProviderRetries
	}
	if opts.NoProgressLimit > 0 {
		out.NoProgressLimit = opts.NoProgressLimit
	}
	if opts.DuplicateToolLimit > 0 {
		out.DuplicateToolLimit = opts.DuplicateToolLimit
	}
	if opts.WallTime > 0 {
		out.WallTime = opts.WallTime
	}
	out.MaxTotalTokens = req.MaxTotalTokens
	out.MaxCostUSD = req.MaxCostUSD
	out.MaxToolCalls = req.MaxToolCalls
	out.MaxLengthContinuations = req.MaxLengthContinuations
	out.MaxStopHookContinuations = req.MaxStopHookContinuations
	return out
}

func projectedHistory(messages []TranscriptMessage) ([]session.Message, error) {
	out := make([]session.Message, 0, len(messages))
	for i, msg := range messages {
		role := strings.ToLower(strings.TrimSpace(msg.Role))
		var sessionRole session.Role
		switch role {
		case string(session.User):
			sessionRole = session.User
		case string(session.Assistant):
			sessionRole = session.Assistant
		case string(session.Tool):
			sessionRole = session.Tool
		default:
			return nil, fmt.Errorf("transcript message %d has unsupported role %q", i, msg.Role)
		}
		out = append(out, session.Message{
			Role:       sessionRole,
			Content:    strings.TrimSpace(msg.Content),
			Reasoning:  strings.TrimSpace(msg.Reasoning),
			ToolCallID: strings.TrimSpace(msg.ToolCallID),
			ToolName:   strings.TrimSpace(msg.ToolName),
			ToolArgs:   strings.TrimSpace(msg.ToolArgs),
		})
	}
	return out, nil
}

func runtimeMessages(messages []session.Message) []TranscriptMessage {
	out := make([]TranscriptMessage, 0, len(messages))
	for _, msg := range messages {
		out = append(out, TranscriptMessage{
			Role:       string(msg.Role),
			Content:    msg.Content,
			Reasoning:  msg.Reasoning,
			ToolCallID: msg.ToolCallID,
			ToolName:   msg.ToolName,
			ToolArgs:   msg.ToolArgs,
		})
	}
	return out
}

func runtimeModelMessages(messages []session.Message) []ModelMessage {
	out := make([]ModelMessage, 0, len(messages))
	for _, msg := range messages {
		out = append(out, ModelMessage{
			Role:       string(msg.Role),
			Content:    msg.Content,
			Reasoning:  msg.Reasoning,
			ToolCallID: msg.ToolCallID,
			ToolName:   msg.ToolName,
			ToolArgs:   msg.ToolArgs,
		})
	}
	return out
}

func runtimeToolDefinitions(defs []provider.ToolDefinition) []tools.ToolDefinition {
	out := make([]tools.ToolDefinition, 0, len(defs))
	for _, def := range defs {
		out = append(out, tools.ToolDefinition{
			Name:         def.Name,
			Title:        def.Title,
			Description:  def.Description,
			InputSchema:  cloneAnyMap(def.InputSchema),
			OutputSchema: cloneAnyMap(def.OutputSchema),
			Strict:       def.Strict,
			Annotations:  cloneAnyMap(def.Annotations),
		})
	}
	return out
}

func providerStreamEvent(ev ModelEvent) provider.StreamEvent {
	return provider.StreamEvent{
		Type:          provider.EventType(ev.Type),
		Text:          ev.Text,
		ToolCalls:     providerToolCalls(ev.ToolCalls),
		Reason:        ev.Reason,
		Usage:         providerUsage(ev.Usage),
		ResponseID:    ev.ResponseID,
		ResponseState: providerState(ev.ResponseState),
		Err:           ev.Err,
	}
}

func providerToolCalls(calls []tools.ToolCall) []provider.ToolCall {
	out := make([]provider.ToolCall, 0, len(calls))
	for _, call := range calls {
		out = append(out, providerToolCall(call))
	}
	return out
}

func providerToolCall(call tools.ToolCall) provider.ToolCall {
	return provider.ToolCall{
		ID:        call.ID,
		Name:      call.Name,
		Args:      call.Args,
		Reasoning: call.Reasoning,
	}
}

func modelState(in *provider.State) *ModelState {
	if in == nil {
		return nil
	}
	return &ModelState{
		Kind:       in.Kind,
		ID:         in.ID,
		Attributes: cloneStringMap(in.Attributes),
	}
}

func providerState(in *ModelState) *provider.State {
	if in == nil {
		return nil
	}
	return &provider.State{
		Kind:       in.Kind,
		ID:         in.ID,
		Attributes: cloneStringMap(in.Attributes),
	}
}

func providerUsage(in ProviderUsage) provider.Usage {
	return provider.Usage{
		InputTokens:       in.InputTokens,
		OutputTokens:      in.OutputTokens,
		ReasoningTokens:   in.ReasoningTokens,
		CacheReadTokens:   in.CacheReadTokens,
		CacheWriteTokens:  in.CacheWriteTokens,
		TotalTokens:       in.TotalTokens,
		CostUSD:           in.CostUSD,
		Source:            provider.UsageSource(in.Source),
		Available:         in.Available,
		WindowInputTokens: in.WindowInputTokens,
	}
}

func projectedTurnResult(ids projectedIDs, in engine.Result) ProjectedTurnResult {
	out := ProjectedTurnResult{
		RunID:              RunID(ids.runID),
		ThreadID:           ThreadID(ids.threadID),
		TurnID:             TurnID(ids.turnID),
		Status:             TurnStatus(in.Status),
		Output:             in.Output,
		Metrics:            runtimeMetrics(in.Metrics),
		Transcript:         runtimeMessages(in.Messages),
		CompletionReason:   string(in.CompletionReason),
		ContinuationReason: string(in.ContinuationReason),
		FinishReason:       string(in.FinishReason),
		RawFinishReason:    in.RawFinishReason,
		FinishInferred:     in.FinishInferred,
		Signal:             runtimeTurnSignal(in.ControlSignal),
	}
	if in.Err != nil {
		out.Error = in.Err.Error()
	}
	return out
}

func runtimeMetrics(in engine.RunMetrics) RunMetrics {
	return RunMetrics{
		ProviderUsage: runtimeProviderUsage(in.Usage),
		Steps:         in.Steps,
		LLMRequests:   in.LLMRequests,
		ToolCalls:     in.ToolCalls,
		Compactions:   in.Compactions,
		Retries:       in.Retries,
		WallTimeMS:    in.WallTimeMS,
	}
}

func runtimeProviderUsage(in provider.Usage) ProviderUsage {
	in = in.Normalized()
	return ProviderUsage{
		InputTokens:       in.InputTokens,
		OutputTokens:      in.OutputTokens,
		ReasoningTokens:   in.ReasoningTokens,
		CacheReadTokens:   in.CacheReadTokens,
		CacheWriteTokens:  in.CacheWriteTokens,
		TotalTokens:       in.TotalTokens,
		CostUSD:           in.CostUSD,
		Source:            string(in.Source),
		Available:         in.Available,
		WindowInputTokens: in.WindowInputTokens,
	}
}

func runtimeTurnSignal(in *engine.ControlSignal) *TurnSignal {
	if in == nil {
		return nil
	}
	return &TurnSignal{
		Disposition: SignalDisposition(in.Disposition),
		Name:        in.Name,
		CallID:      in.CallID,
		Payload:     cloneAnyMap(in.Payload),
		OutputText:  in.OutputText,
		ArgsHash:    in.ArgsHash,
		Labels:      cloneStringMap(in.Labels),
	}
}

func engineLabels(in RunLabels) engine.RunLabels {
	return engine.RunLabels{
		Correlation: cloneStringMap(in.Correlation),
		Host:        cloneStringMap(in.Host),
	}
}

func providerRequestLabels(in provider.RequestLabels) RunLabels {
	return RunLabels{
		Correlation: cloneStringMap(in.Correlation),
		Host:        cloneStringMap(in.Host),
	}
}

func engineTurnCompletionPolicy(policy TurnCompletionPolicy) (engine.CompletionPolicy, error) {
	switch policy {
	case "":
		return engine.CompletionNaturalStop, nil
	case TurnCompletionNaturalStop:
		return engine.CompletionNaturalStop, nil
	case TurnCompletionExplicitSignal:
		return engine.CompletionExplicitSignal, nil
	default:
		return "", fmt.Errorf("unsupported completion policy %q", policy)
	}
}

func engineTurnSignalSpec(spec TurnSignalSpec, policy engine.CompletionPolicy) (engine.ControlSpec, error) {
	if len(spec.Definitions) == 0 && spec.Project == nil {
		if policy == engine.CompletionExplicitSignal {
			return engine.ControlSpec{}, errors.New("signal spec is required when completion policy is explicit_signal")
		}
		return engine.ControlSpec{
			Definitions: []provider.ToolDefinition{},
			Project: func(provider.ToolCall) (engine.ControlSignal, bool, error) {
				return engine.ControlSignal{}, false, nil
			},
		}, nil
	}
	out := engine.ControlSpec{
		Definitions: make([]provider.ToolDefinition, 0, len(spec.Definitions)),
	}
	for _, def := range spec.Definitions {
		name := strings.TrimSpace(def.Name)
		if name == "" {
			continue
		}
		out.Definitions = append(out.Definitions, provider.ToolDefinition{
			Name:         name,
			Title:        strings.TrimSpace(def.Title),
			Description:  strings.TrimSpace(def.Description),
			InputSchema:  cloneAnyMap(def.InputSchema),
			OutputSchema: cloneAnyMap(def.OutputSchema),
			Strict:       def.Strict,
			Annotations:  cloneAnyMap(def.Annotations),
		})
	}
	if spec.Project != nil {
		out.Project = func(call provider.ToolCall) (engine.ControlSignal, bool, error) {
			signal, ok, err := spec.Project(tools.ToolCall{
				ID:        call.ID,
				Name:      call.Name,
				Args:      call.Args,
				Reasoning: call.Reasoning,
			})
			if err != nil || !ok {
				return engine.ControlSignal{}, ok, err
			}
			return engine.ControlSignal{
				Disposition: engine.ControlDisposition(signal.Disposition),
				Name:        signal.Name,
				CallID:      signal.CallID,
				Payload:     cloneAnyMap(signal.Payload),
				OutputText:  signal.OutputText,
				ArgsHash:    signal.ArgsHash,
				Labels:      cloneStringMap(signal.Labels),
			}, true, nil
		}
	}
	if len(out.Definitions) == 0 {
		return engine.ControlSpec{}, errors.New("signal spec must include at least one named definition")
	}
	if out.Project == nil {
		return engine.ControlSpec{}, errors.New("signal spec projector is required")
	}
	return out, nil
}

func cloneAnyMap(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	out := make(map[string]any, len(in))
	for key, value := range in {
		out[key] = cloneAny(value)
	}
	return out
}

func cloneAny(value any) any {
	switch v := value.(type) {
	case map[string]any:
		return cloneAnyMap(v)
	case []any:
		out := make([]any, len(v))
		for i, item := range v {
			out[i] = cloneAny(item)
		}
		return out
	case []string:
		return append([]string(nil), v...)
	case map[string]string:
		return cloneStringMap(v)
	default:
		return value
	}
}
