package hostscaffold

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

type Profile string

const (
	ProfileMemory             Profile = "memory"
	ProfileDurableBasic       Profile = "durable-basic"
	ProfileApproval           Profile = "approval"
	ProfileProductionRecovery Profile = "production-recovery"
	ProfileSubAgent           Profile = "subagent"
)

type Config struct {
	Profile Profile
	Package string
}

type File struct {
	Name    string
	Content []byte
}

//go:embed templates/*.tmpl fixtures/approval/approval_test.go fixtures/durable-basic/recovery_test.go fixtures/production-recovery/recovery_test.go
var templates embed.FS

func Profiles() []Profile {
	return []Profile{ProfileApproval, ProfileDurableBasic, ProfileMemory, ProfileProductionRecovery, ProfileSubAgent}
}

func ParseProfile(value string) (Profile, error) {
	profile := Profile(strings.TrimSpace(value))
	if slices.Contains(Profiles(), profile) {
		return profile, nil
	}
	return "", fmt.Errorf("unsupported profile %q; choose %s", value, joinProfiles(Profiles()))
}

func Generate(cfg Config) ([]File, error) {
	if !token.IsIdentifier(cfg.Package) || token.Lookup(cfg.Package).IsKeyword() {
		return nil, fmt.Errorf("invalid Go package name %q", cfg.Package)
	}
	profile, err := ParseProfile(string(cfg.Profile))
	if err != nil {
		return nil, err
	}
	parsed, err := template.New("hostscaffold").Option("missingkey=error").ParseFS(templates, "templates/*.tmpl")
	if err != nil {
		return nil, err
	}
	data := templateData{
		Package:            cfg.Package,
		Profile:            profile,
		Durable:            profile == ProfileDurableBasic || profile == ProfileProductionRecovery,
		DurableBasic:       profile == ProfileDurableBasic,
		Approval:           profile == ProfileApproval,
		ProductionRecovery: profile == ProfileProductionRecovery,
		SubAgent:           profile == ProfileSubAgent || profile == ProfileProductionRecovery,
		NeedsSort:          profile == ProfileDurableBasic || profile == ProfileProductionRecovery,
		NeedsStrings:       profile == ProfileDurableBasic || profile == ProfileProductionRecovery,
	}
	profileName := strings.ReplaceAll(string(profile), "-", "_")
	outputs := []struct {
		template string
		name     string
	}{
		{template: "composition.go.tmpl", name: fmt.Sprintf("floret_%s.gen.go", profileName)},
		{template: "composition_test.go.tmpl", name: fmt.Sprintf("floret_%s.gen_test.go", profileName)},
	}
	files := make([]File, 0, len(outputs))
	for _, output := range outputs {
		var rendered bytes.Buffer
		if err := parsed.ExecuteTemplate(&rendered, output.template, data); err != nil {
			return nil, err
		}
		formatted, err := format.Source(rendered.Bytes())
		if err != nil {
			return nil, fmt.Errorf("format generated %s: %w", output.name, err)
		}
		files = append(files, File{Name: filepath.Clean(output.name), Content: formatted})
	}
	fixturePath := ""
	switch profile {
	case ProfileApproval:
		fixturePath = "fixtures/approval/approval_test.go"
	case ProfileDurableBasic:
		fixturePath = "fixtures/durable-basic/recovery_test.go"
	case ProfileProductionRecovery:
		fixturePath = "fixtures/production-recovery/recovery_test.go"
	}
	if fixturePath != "" {
		fixture, err := templates.ReadFile(fixturePath)
		if err != nil {
			return nil, err
		}
		packageLine := []byte("package composition\n")
		if !bytes.Contains(fixture, packageLine) {
			return nil, fmt.Errorf("generated %s behavior fixture has no composition package declaration", profile)
		}
		generatedPackageLine := []byte(fmt.Sprintf(
			"// Code generated by floret-host-init v1 for profile %s. Host-owned; review before editing.\n\npackage %s\n",
			profile,
			cfg.Package,
		))
		fixture = bytes.Replace(fixture, packageLine, generatedPackageLine, 1)
		formatted, err := format.Source(fixture)
		if err != nil {
			return nil, fmt.Errorf("format generated %s behavior test: %w", profile, err)
		}
		files = append(files, File{
			Name:    fmt.Sprintf("floret_%s_behavior.gen_test.go", profileName),
			Content: formatted,
		})
	}
	return files, nil
}

type templateData struct {
	Package            string
	Profile            Profile
	Durable            bool
	DurableBasic       bool
	Approval           bool
	ProductionRecovery bool
	SubAgent           bool
	NeedsSort          bool
	NeedsStrings       bool
}

func joinProfiles(profiles []Profile) string {
	values := make([]string, len(profiles))
	for index, profile := range profiles {
		values[index] = string(profile)
	}
	return strings.Join(values, ", ")
}

var ErrConflict = errors.New("host scaffold output conflicts with an existing file")
