// Code generated by floret-host-init v1 for profile approval. Host-owned; review before editing.

package composition

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/floegence/floret/v2/config"
	floretruntime "github.com/floegence/floret/v2/runtime"
	"github.com/floegence/floret/v2/tools"
)

type floretHostOption func(*floretHostOptionSet) error

type floretHostOptionSet struct {
	turn     []floretruntime.TurnExecutionOption
	subAgent []floretruntime.SubAgentOption
}

func withFloretModelGateway(gateway floretruntime.ModelGateway, identity floretruntime.ModelGatewayIdentity, capabilities floretruntime.ModelGatewayCapabilities) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnModelGateway(gateway, identity, capabilities))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentModelGateway(gateway, identity, capabilities))
		return nil
	}
}

func withFloretReadOnlyTools(items ...tools.Tool) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnReadOnlyTools(items...))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentReadOnlyTools(items...))
		return nil
	}
}

func withFloretEffectfulTools(registry *tools.Registry, gate floretruntime.EffectAuthorizationGate) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnEffectfulTools(registry, gate))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentEffectfulTools(registry, gate))
		return nil
	}
}

func withFloretEventSink(sink floretruntime.EventSink) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnEventSink(sink))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentEventSink(sink))
		return nil
	}
}

func withFloretDynamicToolSurface(surface floretruntime.ToolSurfaceProvider) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnDynamicToolSurface(surface))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentDynamicToolSurface(surface))
		return nil
	}
}

func withFloretIDGenerator(generator func(string) string) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnIDGenerator(generator))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentIDGenerator(generator))
		return nil
	}
}

func withFloretLoopLimits(limits floretruntime.LoopLimits) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnLoopLimits(limits))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentLoopLimits(limits))
		return nil
	}
}

func withFloretCapabilities(capabilities floretruntime.CapabilityOptions) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnCapabilities(capabilities))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentCapabilities(capabilities))
		return nil
	}
}

func withFloretThreadTitleMode(mode floretruntime.ThreadTitleMode) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.turn = append(options.turn, floretruntime.WithTurnThreadTitleMode(mode))
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentThreadTitleMode(mode))
		return nil
	}
}

func withFloretSubAgentRunTimeout(timeout time.Duration) floretHostOption {
	return func(options *floretHostOptionSet) error {
		options.subAgent = append(options.subAgent, floretruntime.WithSubAgentRunTimeout(timeout))
		return nil
	}
}

type floretComposition struct {
	store           *floretruntime.Store
	create          *floretruntime.ThreadCreateHostBinder
	read            *floretruntime.ThreadReadHostBinder
	turn            *floretruntime.TurnExecutionHostBinder
	turnOptions     floretruntime.TurnExecutionHostOptions
	subAgentOptions floretruntime.SubAgentHostOptions
}

type floretThreadCreator interface {
	CreateThread(context.Context, floretruntime.CreateThreadRequest) (floretruntime.ThreadSummary, error)
}

type floretThreadReader interface {
	ReadThread(context.Context, floretruntime.ThreadID) (floretruntime.ThreadSnapshot, error)
}

type floretTurnRunner interface {
	RunTurn(context.Context, floretruntime.RunTurnRequest) (floretruntime.TurnResult, error)
	ReadApprovalQueue(context.Context, floretruntime.ReadApprovalQueueRequest) (floretruntime.ApprovalQueue, error)
	ResolveApproval(context.Context, floretruntime.ResolveApprovalRequest) (floretruntime.ResolveApprovalResult, error)
}

func openFloretComposition(ctx context.Context, cfg config.Config, registry *tools.Registry, gate floretruntime.EffectAuthorizationGate, options ...floretHostOption) (*floretComposition, error) {
	options = append([]floretHostOption{withFloretEffectfulTools(registry, gate)}, options...)
	optionSet := floretHostOptionSet{}
	for index, option := range options {
		if option == nil {
			return nil, fmt.Errorf("floret host option %d is invalid", index)
		}
		if err := option(&optionSet); err != nil {
			return nil, fmt.Errorf("floret host option %d: %w", index, err)
		}
	}
	turnOptions, err := floretruntime.NewTurnExecutionHostOptions(cfg, optionSet.turn...)
	if err != nil {
		return nil, err
	}
	subAgentOptions, err := floretruntime.NewSubAgentHostOptions(cfg, optionSet.subAgent...)
	if err != nil {
		return nil, err
	}
	composition := &floretComposition{store: floretruntime.NewMemoryStore(), turnOptions: turnOptions, subAgentOptions: subAgentOptions}
	err = floretruntime.ConfigureHostCapabilities(composition.store, func(bootstrap *floretruntime.HostBootstrap) error {
		if composition.create, err = floretruntime.NewThreadCreateHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.read, err = floretruntime.NewThreadReadHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.turn, err = floretruntime.NewTurnExecutionHostBinder(bootstrap); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	return composition, nil
}

func (composition *floretComposition) close() error {
	if composition == nil || composition.store == nil {
		return nil
	}
	return composition.store.Close()
}

func (composition *floretComposition) bindThreadCreator(threadID floretruntime.ThreadID, createIntentID floretruntime.CreateIntentID) (floretThreadCreator, error) {
	if composition == nil || composition.create == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.create.Bind(threadID, createIntentID)
}

func (composition *floretComposition) bindThreadReader(ctx context.Context, threadID floretruntime.ThreadID) (floretThreadReader, error) {
	if composition == nil || composition.read == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.read.NewHost(ctx, threadID)
}

func (composition *floretComposition) bindTurnHost(ctx context.Context, threadID floretruntime.ThreadID) (floretTurnRunner, error) {
	if composition == nil || composition.turn == nil {
		return nil, errors.New("floret composition is not open")
	}
	factory, err := composition.turn.Bind(threadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, composition.turnOptions)
}

func validateFloretTurnOutcome(result floretruntime.TurnResult, runErr error) error {
	if err := result.Validate(); err != nil {
		return errors.Join(runErr, fmt.Errorf("invalid turn outcome: %w", err))
	}
	if !result.Status.IsTerminal() {
		return errors.Join(runErr, fmt.Errorf("turn outcome is not terminal: %s", result.Status))
	}
	return runErr
}
