// Code generated by floret-host-init v1 for profile durable-basic. Host-owned; review before editing.

package composition

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/floegence/floret/config"
	floretruntime "github.com/floegence/floret/runtime"
)

type floretComposition struct {
	store       *floretruntime.Store
	create      *floretruntime.ThreadCreateHostBinder
	read        *floretruntime.ThreadReadHostBinder
	turn        *floretruntime.TurnExecutionHostBinder
	turnOptions floretruntime.TurnExecutionHostOptions
}

type floretThreadCreator interface {
	CreateThread(context.Context, floretruntime.CreateThreadRequest) (floretruntime.ThreadSummary, error)
}

type floretThreadReader interface {
	ReadThread(context.Context, floretruntime.ThreadID) (floretruntime.ThreadSnapshot, error)
	ReadThreadOverview(context.Context, floretruntime.ThreadID) (floretruntime.ThreadOverview, error)
}

type floretTurnRunner interface {
	RunTurn(context.Context, floretruntime.RunTurnRequest) (floretruntime.TurnResult, error)
}

type floretDurableRoot struct {
	ThreadID         floretruntime.ThreadID
	Profile          string
	SubAgentsEnabled bool
}

type floretRootCatalog interface {
	ListFloretRoots(context.Context) ([]floretDurableRoot, error)
}

type FloretRecoveryRequiredTarget struct {
	ThreadID       floretruntime.ThreadID
	ParentThreadID floretruntime.ThreadID
	TurnID         floretruntime.TurnID
	RunID          floretruntime.RunID
}

type FloretRecoveryRequiredError struct {
	Targets []FloretRecoveryRequiredTarget
}

func (e *FloretRecoveryRequiredError) Error() string {
	return "floret durable host requires interrupted-turn recovery"
}
func openFloretComposition(ctx context.Context, databasePath string, startup floretruntime.SQLiteStartupRequest, storeOptions []floretruntime.SQLiteStoreOption, catalog floretRootCatalog, cfg config.Config, options ...floretruntime.TurnExecutionOption) (*floretComposition, error) {
	turnOptions, err := floretruntime.NewTurnExecutionOptions(cfg, options...)
	if err != nil {
		return nil, err
	}
	startupResult, err := floretruntime.StartSQLiteStore(ctx, databasePath, startup, storeOptions...)
	if err != nil {
		return nil, err
	}
	composition := &floretComposition{store: startupResult.Store, turnOptions: turnOptions}
	err = floretruntime.ConfigureHostCapabilities(composition.store, func(bootstrap *floretruntime.HostBootstrap) error {
		if composition.create, err = floretruntime.NewThreadCreateHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.read, err = floretruntime.NewThreadReadHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.turn, err = floretruntime.NewTurnExecutionHostBinder(bootstrap); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	if err := composition.blockInterruptedRoots(ctx, catalog); err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	return composition, nil
}

func (composition *floretComposition) close() error {
	if composition == nil || composition.store == nil {
		return nil
	}
	return composition.store.Close()
}

func (composition *floretComposition) bindThreadCreator(threadID floretruntime.ThreadID, createIntentID floretruntime.CreateIntentID) (floretThreadCreator, error) {
	if composition == nil || composition.create == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.create.Bind(threadID, createIntentID)
}

func (composition *floretComposition) bindThreadReader(ctx context.Context, threadID floretruntime.ThreadID) (floretThreadReader, error) {
	if composition == nil || composition.read == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.read.NewHost(ctx, threadID)
}

func (composition *floretComposition) bindTurnHost(ctx context.Context, threadID floretruntime.ThreadID) (floretTurnRunner, error) {
	if composition == nil || composition.turn == nil {
		return nil, errors.New("floret composition is not open")
	}
	factory, err := composition.turn.Bind(threadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, composition.turnOptions)
}

func validateFloretTurnOutcome(result floretruntime.TurnResult, runErr error) error {
	if err := result.Validate(); err != nil {
		return errors.Join(runErr, fmt.Errorf("invalid turn outcome: %w", err))
	}
	if !result.Status.IsTerminal() {
		return errors.Join(runErr, fmt.Errorf("turn outcome is not terminal: %s", result.Status))
	}
	return runErr
}

func (composition *floretComposition) blockInterruptedRoots(ctx context.Context, catalog floretRootCatalog) error {
	if catalog == nil {
		return errors.New("durable-basic requires a root catalog")
	}
	roots, err := catalog.ListFloretRoots(ctx)
	if err != nil {
		return fmt.Errorf("list Floret roots: %w", err)
	}
	sort.Slice(roots, func(left, right int) bool { return roots[left].ThreadID < roots[right].ThreadID })
	seen := make(map[floretruntime.ThreadID]struct{}, len(roots))
	targets := make([]FloretRecoveryRequiredTarget, 0)
	for _, root := range roots {
		if strings.TrimSpace(string(root.ThreadID)) == "" {
			return errors.New("durable-basic root catalog contains an empty thread id")
		}
		if _, exists := seen[root.ThreadID]; exists {
			return fmt.Errorf("durable-basic root catalog repeats thread %q", root.ThreadID)
		}
		seen[root.ThreadID] = struct{}{}
		if root.Profile != "durable-basic" || root.SubAgentsEnabled {
			return fmt.Errorf("durable-basic cannot prove root %q has no SubAgent authority", root.ThreadID)
		}
		reader, err := composition.bindThreadReader(ctx, root.ThreadID)
		if err != nil {
			return err
		}
		overview, err := reader.ReadThreadOverview(ctx, root.ThreadID)
		if err != nil {
			return err
		}
		if overview.Thread.Status == floretruntime.ThreadStatusRunning {
			return fmt.Errorf("durable-basic root %q still has an active owner", root.ThreadID)
		}
		if overview.Thread.Status == floretruntime.ThreadStatusInterrupted {
			if overview.Thread.LatestTurnID == "" || overview.Thread.LatestRunID == "" {
				return fmt.Errorf("durable-basic interrupted root %q has incomplete turn authority", root.ThreadID)
			}
			targets = append(targets, FloretRecoveryRequiredTarget{
				ThreadID: root.ThreadID,
				TurnID:   overview.Thread.LatestTurnID,
				RunID:    overview.Thread.LatestRunID,
			})
		}
	}
	if len(targets) == 0 {
		return nil
	}
	owned := append([]FloretRecoveryRequiredTarget(nil), targets...)
	return &FloretRecoveryRequiredError{Targets: owned}
}
