// Code generated by floret-host-init v1 for profile memory. Host-owned; review before editing.

package composition

import (
	"context"
	"testing"

	"github.com/floegence/floret/v2/config"
	floretruntime "github.com/floegence/floret/v2/runtime"
)

func TestFloretGeneratedCompositionSmoke(t *testing.T) {
	ctx := context.Background()
	cfg := config.Config{
		Provider: config.ProviderFake, Model: "fake-model", FakeResponse: "Hello from Floret.",
		AgentProfile: config.AgentProfile{ID: "smoke-agent", Name: "Smoke Agent", SystemPrompt: "Answer briefly."},
	}
	composition, err := openFloretComposition(ctx, cfg)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := composition.close(); err != nil {
			t.Error(err)
		}
	})

	threadID := floretruntime.ThreadID("smoke-thread")
	intentID := floretruntime.CreateIntentID("create-smoke-thread")
	creator, err := composition.bindThreadCreator(threadID, intentID)
	if err != nil {
		t.Fatal(err)
	}
	thread, err := creator.CreateThread(ctx, floretruntime.CreateThreadRequest{ThreadID: threadID, CreateIntentID: intentID})
	if err != nil {
		t.Fatal(err)
	}
	turns, err := composition.bindTurnHost(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	result, runErr := turns.RunTurn(ctx, floretruntime.RunTurnRequest{
		ThreadID: thread.ID, TurnID: "smoke-turn", RunID: "smoke-run",
		Input: floretruntime.TurnInput{Text: "Say hello."},
	})
	if err := validateFloretTurnOutcome(result, runErr); err != nil {
		t.Fatal(err)
	}
	reader, err := composition.bindThreadReader(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	snapshot, err := reader.ReadThread(ctx, thread.ID)
	if err != nil {
		t.Fatal(err)
	}
	if snapshot.ID != thread.ID || result.Output != "Hello from Floret." {
		t.Fatalf("unexpected smoke result: thread=%#v turn=%#v", snapshot, result)
	}
}
