// Package agentharness exposes the host/UI durable conversation API.
//
// AgentHarness owns durable threads backed by sessiontree.Repo. Thread.Run,
// Thread.Retry, Thread.MoveTo, and Thread.Compact are safe to call concurrently
// across different ThreadIDs, including source and forked threads. A single
// durable ThreadID admits at most one active turn or mutation at a time; callers
// that race the same thread receive ErrActiveTurn before new turn entries are
// appended. This serialization is enforced through the repository turn lease
// contract when the repo implements sessiontree.TurnLeaseRepo, so two harnesses
// sharing one durable repo observe the same active-turn invariant.
//
// The lower-level engine remains a turn executor. Harness callers configure
// engine behavior through TurnPolicy and LoopLimits rather than raw
// engine.Options so run identity, provider/model identity, and control tool
// definitions are generated by the harness for the active durable thread.
package agentharness
