package modelcatalog

var text = []string{"text"}
var vision = []string{"text", "image"}

var providers = []Provider{
	{
		ID:           ProviderFake,
		Name:         "Fake",
		API:          APIFake,
		DefaultModel: "fake-model",
		Custom:       true,
		Models: []Model{
			{ID: "fake-model", Name: "Fake model", ContextWindow: 128000, MaxTokens: 4096, Input: text},
		},
	},
	{
		ID:             ProviderOpenAI,
		Name:           "OpenAI",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.openai.com/v1",
		DefaultModel:   "gpt-5.4",
		EnvKeys:        []string{"OPENAI_API_KEY"},
		Custom:         true,
		Cache:          CacheCapability{PromptCacheKey: true, PromptCacheRetention: true},
		Models: []Model{
			{ID: "gpt-5.5", Name: "GPT-5.5", ContextWindow: 1050000, MaxTokens: 128000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 15, OutputPerMTok: 120}},
			{ID: "gpt-5.4", Name: "GPT-5.4", ContextWindow: 1050000, MaxTokens: 128000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 10, OutputPerMTok: 80}},
			{ID: "gpt-5.4-mini", Name: "GPT-5.4 mini", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 1.25, OutputPerMTok: 10}},
			{ID: "gpt-5.4-nano", Name: "GPT-5.4 nano", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 0.25, OutputPerMTok: 2}},
			{ID: "gpt-5.2", Name: "GPT-5.2", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true},
			{ID: "gpt-5.2-mini", Name: "GPT-5.2 mini", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true},
			{ID: "gpt-5", Name: "GPT-5", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true},
			{ID: "gpt-5-mini", Name: "GPT-5 mini", ContextWindow: 400000, MaxTokens: 128000, Input: vision, Reasoning: true},
		},
	},
	{
		ID:             ProviderAnthropic,
		Name:           "Anthropic",
		API:            APIAnthropicMessages,
		DefaultBaseURL: "https://api.anthropic.com/v1",
		DefaultModel:   "claude-sonnet-4-6",
		EnvKeys:        []string{"ANTHROPIC_API_KEY"},
		Custom:         true,
		Cache:          CacheCapability{AnthropicCacheControl: true},
		Models: []Model{
			{ID: "claude-opus-4-7", Name: "Claude Opus 4.7", ContextWindow: 1000000, MaxTokens: 128000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 15, OutputPerMTok: 75}},
			{ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6", ContextWindow: 1000000, MaxTokens: 64000, Input: vision, Reasoning: true, Cost: Cost{InputPerMTok: 3, OutputPerMTok: 15}},
			{ID: "claude-haiku-4-5-20251001", Name: "Claude Haiku 4.5", ContextWindow: 200000, MaxTokens: 64000, Input: vision, Reasoning: false, Cost: Cost{InputPerMTok: 0.8, OutputPerMTok: 4}},
		},
	},
	{
		ID:             ProviderGoogle,
		Name:           "Google Gemini",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
		DefaultModel:   "gemini-3.1-pro-preview",
		EnvKeys:        []string{"GEMINI_API_KEY", "GOOGLE_API_KEY"},
		Models: []Model{
			{ID: "gemini-3.1-pro-preview", Name: "Gemini 3.1 Pro Preview", ContextWindow: 1000000, MaxTokens: 65536, Input: vision, Reasoning: true},
			{ID: "gemini-3.1-flash-preview", Name: "Gemini 3.1 Flash Preview", ContextWindow: 1000000, MaxTokens: 65536, Input: vision, Reasoning: true},
			{ID: "gemini-2.5-pro", Name: "Gemini 2.5 Pro", ContextWindow: 1000000, MaxTokens: 65536, Input: vision, Reasoning: true},
			{ID: "gemini-2.5-flash", Name: "Gemini 2.5 Flash", ContextWindow: 1000000, MaxTokens: 65536, Input: vision, Reasoning: true},
		},
	},
	{
		ID:             ProviderMoonshot,
		Name:           "Moonshot",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.moonshot.cn/v1",
		DefaultModel:   "kimi-k2.6",
		EnvKeys:        []string{"MOONSHOT_API_KEY", "KIMI_API_KEY"},
		Models: []Model{
			{ID: "kimi-k2.6", Name: "Kimi K2.6", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true},
			{ID: "kimi-k2.6-thinking", Name: "Kimi K2.6 Thinking", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true},
		},
	},
	{
		ID:             ProviderChatGLM,
		Name:           "ChatGLM / Z.ai",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.z.ai/api/paas/v4",
		DefaultModel:   "glm-5.1",
		EnvKeys:        []string{"ZAI_API_KEY", "CHATGLM_API_KEY"},
		Models: []Model{
			{ID: "glm-5.1", Name: "GLM 5.1", ContextWindow: 200000, MaxTokens: 128000, Input: text, Reasoning: true},
			{ID: "glm-4.5", Name: "GLM 4.5", ContextWindow: 128000, MaxTokens: 96000, Input: text, Reasoning: true},
		},
	},
	{
		ID:             ProviderDeepSeek,
		Name:           "DeepSeek",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.deepseek.com",
		DefaultModel:   "deepseek-v4-pro",
		EnvKeys:        []string{"DEEPSEEK_API_KEY"},
		Models: []Model{
			{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro", ContextWindow: 1000000, MaxTokens: 384000, Input: text, Reasoning: true},
			{ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash", ContextWindow: 1000000, MaxTokens: 384000, Input: text, Reasoning: true},
			{ID: "deepseek-chat", Name: "DeepSeek Chat", ContextWindow: 128000, MaxTokens: 8192, Input: text},
			{ID: "deepseek-reasoner", Name: "DeepSeek Reasoner", ContextWindow: 128000, MaxTokens: 8192, Input: text, Reasoning: true},
		},
	},
	{
		ID:             ProviderQwen,
		Name:           "Qwen",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
		DefaultModel:   "qwen3.6-plus",
		EnvKeys:        []string{"DASHSCOPE_API_KEY", "QWEN_API_KEY", "ALIBABA_CLOUD_API_KEY"},
		Models: []Model{
			{ID: "qwen3.6-plus", Name: "Qwen 3.6 Plus", ContextWindow: 1000000, MaxTokens: 65536, Input: text, Reasoning: true},
			{ID: "qwen3.6-plus-2026-04-02", Name: "Qwen 3.6 Plus snapshot", ContextWindow: 1000000, MaxTokens: 65536, Input: text, Reasoning: true},
			{ID: "qwen3.6-flash", Name: "Qwen 3.6 Flash", ContextWindow: 1000000, MaxTokens: 65536, Input: text, Reasoning: true},
			{ID: "qwen3.6-flash-2026-04-16", Name: "Qwen 3.6 Flash snapshot", ContextWindow: 1000000, MaxTokens: 65536, Input: text, Reasoning: true},
		},
	},
	{
		ID:             ProviderOpenRouter,
		Name:           "OpenRouter",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://openrouter.ai/api/v1",
		DefaultModel:   "moonshotai/kimi-k2.6",
		EnvKeys:        []string{"OPENROUTER_API_KEY"},
		Models: []Model{
			{ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true, OpenAIModelID: "moonshotai/kimi-k2.6"},
			{ID: "anthropic/claude-sonnet-4.6", Name: "Claude Sonnet 4.6", ContextWindow: 1000000, MaxTokens: 64000, Input: vision, Reasoning: true, OpenAIModelID: "anthropic/claude-sonnet-4.6"},
			{ID: "openai/gpt-5.4", Name: "GPT-5.4", ContextWindow: 1050000, MaxTokens: 128000, Input: vision, Reasoning: true, OpenAIModelID: "openai/gpt-5.4"},
		},
	},
	{
		ID:             ProviderXAI,
		Name:           "xAI",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.x.ai/v1",
		DefaultModel:   "grok-4.20-0309-reasoning",
		EnvKeys:        []string{"XAI_API_KEY"},
		Models: []Model{
			{ID: "grok-4.20-0309-reasoning", Name: "Grok 4.20 Reasoning", ContextWindow: 256000, MaxTokens: 128000, Input: vision, Reasoning: true},
			{ID: "grok-4.20", Name: "Grok 4.20", ContextWindow: 256000, MaxTokens: 128000, Input: vision},
		},
	},
	{
		ID:             ProviderGroq,
		Name:           "Groq",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.groq.com/openai/v1",
		DefaultModel:   "openai/gpt-oss-120b",
		EnvKeys:        []string{"GROQ_API_KEY"},
		Models: []Model{
			{ID: "openai/gpt-oss-120b", Name: "GPT OSS 120B", ContextWindow: 131072, MaxTokens: 65536, Input: text, Reasoning: true, OpenAIModelID: "openai/gpt-oss-120b"},
			{ID: "openai/gpt-oss-20b", Name: "GPT OSS 20B", ContextWindow: 131072, MaxTokens: 65536, Input: text, Reasoning: true, OpenAIModelID: "openai/gpt-oss-20b"},
		},
	},
	{
		ID:             ProviderCerebras,
		Name:           "Cerebras",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.cerebras.ai/v1",
		DefaultModel:   "zai-glm-4.7",
		EnvKeys:        []string{"CEREBRAS_API_KEY"},
		Models: []Model{
			{ID: "zai-glm-4.7", Name: "Z.ai GLM 4.7", ContextWindow: 128000, MaxTokens: 65536, Input: text, Reasoning: true},
			{ID: "qwen-3-coder-480b", Name: "Qwen3 Coder 480B", ContextWindow: 128000, MaxTokens: 65536, Input: text},
		},
	},
	{
		ID:             ProviderMistral,
		Name:           "Mistral",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.mistral.ai/v1",
		DefaultModel:   "devstral-medium-latest",
		EnvKeys:        []string{"MISTRAL_API_KEY"},
		Models: []Model{
			{ID: "devstral-medium-latest", Name: "Devstral Medium", ContextWindow: 131072, MaxTokens: 65536, Input: text},
			{ID: "mistral-large-latest", Name: "Mistral Large", ContextWindow: 131072, MaxTokens: 65536, Input: text},
		},
	},
	{
		ID:             ProviderTogether,
		Name:           "Together",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.together.xyz/v1",
		DefaultModel:   "moonshotai/Kimi-K2.6",
		EnvKeys:        []string{"TOGETHER_API_KEY"},
		Models: []Model{
			{ID: "moonshotai/Kimi-K2.6", Name: "Kimi K2.6", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true, OpenAIModelID: "moonshotai/Kimi-K2.6"},
			{ID: "Qwen/Qwen3-Coder-480B-A35B-Instruct", Name: "Qwen3 Coder 480B", ContextWindow: 262144, MaxTokens: 131072, Input: text, OpenAIModelID: "Qwen/Qwen3-Coder-480B-A35B-Instruct"},
		},
	},
	{
		ID:             ProviderFireworks,
		Name:           "Fireworks",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.fireworks.ai/inference/v1",
		DefaultModel:   "accounts/fireworks/models/kimi-k2p6",
		EnvKeys:        []string{"FIREWORKS_API_KEY"},
		Models: []Model{
			{ID: "accounts/fireworks/models/kimi-k2p6", Name: "Kimi K2.6", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true},
			{ID: "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct", Name: "Qwen3 Coder 480B", ContextWindow: 262144, MaxTokens: 131072, Input: text},
		},
	},
	{
		ID:             ProviderVercelAIGateway,
		Name:           "Vercel AI Gateway",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://ai-gateway.vercel.sh/v1",
		DefaultModel:   "zai/glm-5.1",
		EnvKeys:        []string{"AI_GATEWAY_API_KEY"},
		Models: []Model{
			{ID: "zai/glm-5.1", Name: "GLM 5.1", ContextWindow: 200000, MaxTokens: 128000, Input: text, Reasoning: true},
			{ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6", ContextWindow: 256000, MaxTokens: 96000, Input: text, Reasoning: true},
			{ID: "openai/gpt-5.4", Name: "GPT-5.4", ContextWindow: 1050000, MaxTokens: 128000, Input: vision, Reasoning: true},
		},
	},
	{
		ID:             ProviderOllama,
		Name:           "Ollama",
		API:            APIOpenAIChat,
		DefaultBaseURL: "http://127.0.0.1:11434/v1",
		DefaultModel:   "gpt-oss:20b",
		Custom:         true,
		Models: []Model{
			{ID: "gpt-oss:20b", Name: "GPT OSS 20B local", ContextWindow: 131072, MaxTokens: 32768, Input: text, Reasoning: true},
			{ID: "qwen3-coder:latest", Name: "Qwen3 Coder local", ContextWindow: 131072, MaxTokens: 32768, Input: text},
			{ID: "llama3.1:8b", Name: "Llama 3.1 8B local", ContextWindow: 128000, MaxTokens: 8192, Input: text},
		},
	},
	{
		ID:             ProviderOpenAICompatible,
		Name:           "OpenAI-compatible",
		API:            APIOpenAIChat,
		DefaultBaseURL: "https://api.example.com/v1",
		DefaultModel:   "custom-model",
		EnvKeys:        []string{"FLORET_API_KEY", "OPENAI_COMPATIBLE_API_KEY"},
		Custom:         true,
		Models: []Model{
			{ID: "custom-model", Name: "Custom model", ContextWindow: 128000, MaxTokens: 8192, Input: text},
		},
	},
}
