package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var readMethods = map[string]bool{
	"ArtifactClosure":      true,
	"CanonicalTurnEntries": true, "EffectAttempt": true, "Entries": true, "Entry": true,
	"ListCanonicalTurns": true, "ListSubAgentInputs": true, "ListThreads": true,
	"Path": true, "PathPage": true, "PendingAutomaticThreadTitles": true,
	"ProviderState": true, "ReadAgentTodoState": true,
	"ReadArtifact": true, "ReadCanonicalTurn": true, "ReadCompaction": true,
	"ReadPendingToolCompletion": true, "ReadSubAgentInput": true,
	"Thread": true, "ThreadTombstone": true,
	"ValidateArtifactForkDestination": true, "ValidateInterruptedTurnResolution": true,
}

var handwritten = map[string]bool{
	"EncodeMemoryState":       true,
	"ListRootThreadInventory": true, "AcceptTurn": true, "ReadAcceptedTurn": true,
}

func main() {
	dir := flag.String("dir", "internal/sessiontree", "sessiontree package directory")
	out := flag.String("out", "internal/sessiontree/backend_repo_generated.go", "generated output")
	flag.Parse()
	fset := token.NewFileSet()
	packages, err := parser.ParseDir(fset, *dir, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go") && info.Name() != filepath.Base(*out)
	}, 0)
	if err != nil {
		panic(err)
	}
	var methods []*ast.FuncDecl
	for _, file := range packages["sessiontree"].Files {
		for _, declaration := range file.Decls {
			method, ok := declaration.(*ast.FuncDecl)
			if !ok || method.Recv == nil || !ast.IsExported(method.Name.Name) || handwritten[method.Name.Name] {
				continue
			}
			star, ok := method.Recv.List[0].Type.(*ast.StarExpr)
			if !ok {
				continue
			}
			identifier, receiverIsIdentifier := star.X.(*ast.Ident)
			if !receiverIsIdentifier || identifier.Name != "MemoryRepo" {
				continue
			}
			methods = append(methods, method)
		}
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name.Name < methods[j].Name.Name })
	var generated bytes.Buffer
	generated.WriteString("// Code generated by genbackendrepo; DO NOT EDIT.\n\npackage sessiontree\n\nimport (\n\t\"context\"\n\n\t\"github.com/floegence/floret/v6/internal/session/artifact\"\n)\n\n")
	for _, method := range methods {
		generateMethod(&generated, fset, method)
	}
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated source: %w\n%s", err, generated.Bytes()))
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		panic(err)
	}
}

func generateMethod(out *bytes.Buffer, fset *token.FileSet, method *ast.FuncDecl) {
	params, arguments := parameters(fset, method.Type.Params)
	results, resultTypes := results(fset, method.Type.Results)
	fmt.Fprintf(out, "func (repo *BackendRepo) %s%s%s {\n", method.Name.Name, params, results)
	for index, resultType := range resultTypes {
		fmt.Fprintf(out, "\tvar result%d %s\n", index, resultType)
	}
	operation := "update"
	if readMethods[method.Name.Name] {
		operation = "view"
	}
	fmt.Fprintf(out, "\terr := repo.%s(ctx, func(memory *MemoryRepo) error {\n", operation)
	if len(resultTypes) == 0 {
		fmt.Fprintf(out, "\t\treturn memory.%s(%s)\n", method.Name.Name, strings.Join(arguments, ", "))
	} else {
		assigned := make([]string, len(resultTypes))
		for index := range assigned {
			assigned[index] = fmt.Sprintf("result%d", index)
		}
		fmt.Fprintf(out, "\t\tvar callErr error\n\t\t%s, callErr = memory.%s(%s)\n\t\treturn callErr\n", strings.Join(assigned, ", "), method.Name.Name, strings.Join(arguments, ", "))
	}
	out.WriteString("\t})\n")
	returns := make([]string, len(resultTypes)+1)
	for index := range resultTypes {
		returns[index] = fmt.Sprintf("result%d", index)
	}
	returns[len(returns)-1] = "err"
	fmt.Fprintf(out, "\treturn %s\n}\n\n", strings.Join(returns, ", "))
}

func parameters(fset *token.FileSet, fields *ast.FieldList) (string, []string) {
	arguments := make([]string, 0)
	index := 0
	for _, field := range fields.List {
		if len(field.Names) == 0 {
			field.Names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("arg%d", index))}
		}
		for _, name := range field.Names {
			if name.Name == "_" {
				name.Name = "ctx"
			}
			argument := name.Name
			if _, variadic := field.Type.(*ast.Ellipsis); variadic {
				argument += "..."
			}
			arguments = append(arguments, argument)
			index++
		}
	}
	return renderFieldList(fset, fields), arguments
}

func results(fset *token.FileSet, fields *ast.FieldList) (string, []string) {
	if fields == nil || len(fields.List) == 0 {
		return "", nil
	}
	types := make([]string, 0)
	for index, field := range fields.List {
		typeName := render(fset, field.Type)
		count := len(field.Names)
		if count == 0 {
			count = 1
		}
		if index == len(fields.List)-1 && typeName == "error" {
			continue
		}
		for range count {
			types = append(types, typeName)
		}
	}
	return " " + renderFieldList(fset, fields), types
}

func renderFieldList(fset *token.FileSet, fields *ast.FieldList) string {
	parts := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		typeName := render(fset, field.Type)
		if len(field.Names) == 0 {
			parts = append(parts, typeName)
			continue
		}
		names := make([]string, len(field.Names))
		for index, name := range field.Names {
			names[index] = name.Name
		}
		parts = append(parts, strings.Join(names, ", ")+" "+typeName)
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func render(fset *token.FileSet, node any) string {
	var output bytes.Buffer
	if err := format.Node(&output, fset, node.(ast.Node)); err != nil {
		panic(err)
	}
	return output.String()
}
