// Code generated by floret-host-init v1 for profile subagent. Host-owned; review before editing.

package composition

import (
	"context"
	"errors"
	"fmt"

	"github.com/floegence/floret/config"
	floretruntime "github.com/floegence/floret/runtime"
)

type floretComposition struct {
	store        *floretruntime.Store
	create       *floretruntime.ThreadCreateHostBinder
	read         *floretruntime.ThreadReadHostBinder
	turn         *floretruntime.TurnExecutionHostBinder
	turnOptions  floretruntime.TurnExecutionHostOptions
	subAgent     *floretruntime.SubAgentHostBinder
	subAgentRead *floretruntime.SubAgentReadHostBinder
}

type floretThreadCreator interface {
	CreateThread(context.Context, floretruntime.CreateThreadRequest) (floretruntime.ThreadSummary, error)
}

type floretThreadReader interface {
	ReadThread(context.Context, floretruntime.ThreadID) (floretruntime.ThreadSnapshot, error)
}

type floretTurnRunner interface {
	RunTurn(context.Context, floretruntime.RunTurnRequest) (floretruntime.TurnResult, error)
}

type floretSubAgentRunner interface {
	SpawnSubAgent(context.Context, floretruntime.SpawnSubAgentRequest) (floretruntime.SubAgentSnapshot, error)
	SendSubAgentInput(context.Context, floretruntime.SendSubAgentInputRequest) (floretruntime.SubAgentSnapshot, error)
	WaitSubAgents(context.Context, floretruntime.WaitSubAgentsRequest) (floretruntime.WaitSubAgentsResult, error)
	CloseSubAgent(context.Context, floretruntime.CloseSubAgentRequest) (floretruntime.SubAgentSnapshot, error)
}

func openFloretComposition(ctx context.Context, cfg config.Config, options ...floretruntime.TurnExecutionOption) (*floretComposition, error) {
	turnOptions, err := floretruntime.NewTurnExecutionOptions(cfg, options...)
	if err != nil {
		return nil, err
	}
	composition := &floretComposition{store: floretruntime.NewMemoryStore(), turnOptions: turnOptions}
	err = floretruntime.ConfigureHostCapabilities(composition.store, func(bootstrap *floretruntime.HostBootstrap) error {
		if composition.create, err = floretruntime.NewThreadCreateHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.read, err = floretruntime.NewThreadReadHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.turn, err = floretruntime.NewTurnExecutionHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.subAgent, err = floretruntime.NewSubAgentHostBinder(bootstrap); err != nil {
			return err
		}
		if composition.subAgentRead, err = floretruntime.NewSubAgentReadHostBinder(bootstrap); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return nil, errors.Join(err, composition.store.Close())
	}
	return composition, nil
}

func (composition *floretComposition) close() error {
	if composition == nil || composition.store == nil {
		return nil
	}
	return composition.store.Close()
}

func (composition *floretComposition) bindThreadCreator(threadID floretruntime.ThreadID, createIntentID floretruntime.CreateIntentID) (floretThreadCreator, error) {
	if composition == nil || composition.create == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.create.Bind(threadID, createIntentID)
}

func (composition *floretComposition) bindThreadReader(ctx context.Context, threadID floretruntime.ThreadID) (floretThreadReader, error) {
	if composition == nil || composition.read == nil {
		return nil, errors.New("floret composition is not open")
	}
	return composition.read.NewHost(ctx, threadID)
}

func (composition *floretComposition) bindTurnHost(ctx context.Context, threadID floretruntime.ThreadID) (floretTurnRunner, error) {
	if composition == nil || composition.turn == nil {
		return nil, errors.New("floret composition is not open")
	}
	factory, err := composition.turn.Bind(threadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, composition.turnOptions)
}

func (composition *floretComposition) bindSubAgentHost(ctx context.Context, parentThreadID floretruntime.ThreadID) (floretSubAgentRunner, error) {
	if composition == nil || composition.subAgent == nil {
		return nil, errors.New("floret composition has no SubAgent capability")
	}
	factory, err := composition.subAgent.Bind(parentThreadID)
	if err != nil {
		return nil, err
	}
	return factory.NewHost(ctx, floretruntime.SubAgentHostOptions{
		Config:                   composition.turnOptions.Config,
		ModelGateway:             composition.turnOptions.ModelGateway,
		ModelGatewayIdentity:     composition.turnOptions.ModelGatewayIdentity,
		ModelGatewayCapabilities: composition.turnOptions.ModelGatewayCapabilities,
		Tools:                    composition.turnOptions.Tools,
		EffectAuthorizationGate:  composition.turnOptions.EffectAuthorizationGate,
		Sink:                     composition.turnOptions.Sink,
		ToolSurfaceProvider:      composition.turnOptions.ToolSurfaceProvider,
		IDGenerator:              composition.turnOptions.IDGenerator,
		LoopLimits:               composition.turnOptions.LoopLimits,
		Capabilities:             composition.turnOptions.Capabilities,
		ThreadTitleMode:          composition.turnOptions.ThreadTitleMode,
	})
}

func validateFloretTurnOutcome(result floretruntime.TurnResult, runErr error) error {
	if err := result.Validate(); err != nil {
		return errors.Join(runErr, fmt.Errorf("invalid turn outcome: %w", err))
	}
	if !result.Status.IsTerminal() {
		return errors.Join(runErr, fmt.Errorf("turn outcome is not terminal: %s", result.Status))
	}
	return runErr
}
